### ISSUE TITLE
Pipeline skips first day

### ISSUE THREAD

**Issue by RiccaDS** [stefan-jansen/zipline-reloaded#100]
Dear Zipline Maintainers,

By running a very basic pipeline I have noticed that on SimplePipelineEngine.run_pipeline call the first day of the data in my csv bundle gets excluded from the pipeline. I don't get the rationale of this. I would expect all days to be included. 
```
bundle_data = load('my_bundle')

my_pipeline = Pipeline(domain=US_EQUITIES)

pipeline_loader = USEquityPricingLoader.without_fx(bundle_data.equity_daily_bar_reader, bundle_data.adjustment_reader)

def choose_loader(column):
    return pipeline_loader

spe = SimplePipelineEngine(get_loader=choose_loader, asset_finder=bundle_data.asset_finder)

results = spe.run_pipeline(my_pipeline,
                           start_naive,
                           end_naive)
print("RESULTS")
display(results)
```

supposing that I have data in my CSV(actually minute data but I don't know this makes a difference) from 2021-08-02  to 2021-08-12, the results to the pipeline call will be:
2021-08-03 00:00:00+00:00   Equity(1 [GOOGL])
2021-08-04 00:00:00+00:00   Equity(1 [GOOGL])
2021-08-05 00:00:00+00:00   Equity(1 [GOOGL])
2021-08-06 00:00:00+00:00   Equity(1 [GOOGL])
2021-08-07 00:00:00+00:00   Equity(1 [GOOGL])
2021-08-08 00:00:00+00:00   Equity(1 [GOOGL])
2021-08-09 00:00:00+00:00   Equity(1 [GOOGL])
2021-08-10 00:00:00+00:00   Equity(1 [GOOGL])
2021-08-11 00:00:00+00:00   Equity(1 [GOOGL])
2021-08-12 00:00:00+00:00   Equity(1 [GOOGL])

This becomes a problem when I attach the pipeline as I don't have access to the 2021-08-02 data through the handle_data(). I only have access to the last record of that day. Any way I can get access to the first day's minute data through the pipeline?
Thank you
Sincerely,
Ricc

**Comment by RiccaDS** [comment]
So I still haven't resolved the issue on the pipeline side. However there was the same problem in other two situations in the zipline code. I don't understand if is a coding error or if it's  voluntary to prohibit trades in the first day. Anyhow, to avoid can_trade() to return a False, I have changed the following code:
        `return ref_start <= session_label.value <= ref_end`
to this:
        ```
return (ref_start_dt.date() == session_label_dt.date() or
                ref_start <= session_label.value <= ref_end)
```
in _protocol.pyx . For the less experts(like I am), this codes need to be compiled with cython by using a setup.py file I can provide if needed. 
Also I have changed 
`if normalized_date < asset.start_date:`
into 
`if normalized_date.date() < asset.start_date.date():`
in algorithm.py to correct order placing blockage.  
I will update as I resolve the pipeline issue.

**Comment by RiccaDS** [comment]
So I got the pipeline issue resolved too. I have substituted this
`mask = lifetimes.start <= raw_dates`
with

```
            def todate(tstamp):
                return np.array([datetime.utcfromtimestamp(tstamp[0] // 10**9).date()])
            
            mapped = np.array(list(map(todate,raw_dates)))
            converted = np.array([datetime.utcfromtimestamp(lifetimes.start[0] // 10**9).date()])

            mask = converted <= mapped

```
in assets/assets.py.
And I changed include_start_date to True in pipeline/engine.py.

**Comment by vaa1234** [comment]
@RiccaDS Hi. I found a similar issue. In trading live mode (launched on the current date, for example), pipeline requests data from the previous day. But the data is returned as of 2 days ago. That is, the data is shifted back one day.

I couldn't fix it.

**Comment by MBounouar** [comment]
Hi, could you provide a reproducible example?

**Comment by vaa1234** [comment]
Example with sharadar zipline bundle. He uses original pipeline from zipline package.
```
from exchange_calendars import get_calendar
import os
import datetime
import time
import numpy as np
import pandas as pd
import zipline.api as algo
from sharadar.pipeline.engine import symbols, symbol
from sharadar.util.run_algo import run_algorithm
from zipline.pipeline import Pipeline
from zipline.pipeline.data import USEquityPricing
from sharadar.util.logger import StrategyLogger
from zipline.pipeline.factors import SimpleMovingAverage, ExponentialWeightedMovingStdDev
from sharadar.pipeline.factors import Exchange, AverageDollarVolume, CustomFactor, IsDomesticCommonStock
from zipline.pipeline.filters import AllPresent, All, StaticAssets, StaticSids
from zipline.finance.execution import MarketOrder, LimitOrder
from zipline.finance.commission import PerShare
from zipline.finance import slippage, commission

from sharadar.live.brokers.ib_broker import IBBroker

from ib_insync import IB, Stock, util as ib_insync_util
import nest_asyncio
log = BacktestLogger(__file__)

def make_pipeline():
    pipeline = Pipeline(
        columns = {
            'close': USEquityPricing.close.latest,
        },
        screen=( StaticAssets([symbol('BRBR')]) )
    )

    return pipeline

def initialize(context):
    algo.attach_pipeline(make_pipeline(), 'pipeline')
    
def handle_data(context, data):
    pass

def before_trading_start(context, data):
    context.candidates = algo.pipeline_output('pipeline')
    log.info('context.candidates: {}'.format(context.candidates))
    
if __name__ == "__main__":

    xnys = get_calendar("XNYS")

    run_algorithm(
        handle_data=handle_data,
        initialize=initialize,
        before_trading_start=before_trading_start,
        data_frequency = 'minute',
        broker=IBBroker(tws_uri='localhost:7496:1239'),
        state_filename='./statefile',
        trading_calendar = xnys
        # bundle=bundle_name,
    )
```
Result:

```
[2022-05-18 14:04:01] INFO: Connecting: localhost:7496:1239
[2022-05-18 14:04:01] INFO: [2104] Market data farm connection is OK:usfarm.nj (-1)
[2022-05-18 14:04:01] INFO: [2104] Market data farm connection is OK:usfarm (-1)
[2022-05-18 14:04:01] INFO: [2106] HMDS data farm connection is OK:ushmds (-1)
[2022-05-18 14:04:01] INFO: [2158] Sec-def data farm connection is OK:secdefnj (-1)
[2022-05-18 14:04:01] INFO: Managed accounts: ['DU12345']
[2022-05-18 14:04:01] INFO: Local-Broker Time Skew: 0 days 00:00:00.598403
[2022-05-18 14:04:01] INFO: Using bundle 'sharadar'.
[2022-05-18 14:04:01] INFO: Live Trading on 2022-05-18.
[2022-05-18 14:04:01] INFO: Initialized blotter_live
[2022-05-18 14:04:01] INFO: Loading state from ./statefile
[2022-05-18 14:04:01] INFO: initialization done
[2022-05-18 14:04:01] INFO: (self.get_datetime() : 2022-05-18 00:00:00+00:00
[2022-05-18 14:04:01] INFO: today in _pipeline_output : 2022-05-17 00:00:00+00:00
[2022-05-18 14:04:01] INFO: KeyError self.run_pipeline
Pipeline from 2022-05-17 to 2022-05-17  [####################################]  100%[2022-05-18 14:04:02] INFO: Pipeline from 2022-05-17 to 2022-05-17 completed in 0:00:00.
[2022-05-18 14:04:02] INFO: (self.get_datetime() : 2022-05-18 00:00:00+00:00
[2022-05-18 14:04:02] INFO: today in _pipeline_output : 2022-05-17 00:00:00+00:00
[2022-05-18 14:04:02] INFO: self._pipeline_cache.get
[2022-05-18 14:04:02] INFO: context.candidates:                        close
Equity(110458 [BRBR])  24.39
```

If we look at the data on the history:
```
from sharadar.pipeline.engine import prices as get_pricing, symbols
get_pricing(symbols(['BRBR']), '2022-05-17', '2022-05-17', 'close', 2)

2022-05-13 00:00:00+00:00    24.72
2022-05-16 00:00:00+00:00    24.39
2022-05-17 00:00:00+00:00    25.82
Freq: C, Name: Equity(110458 [BRBR]), dtype: float64
```

Close on 2022-05-17 it should be 25.82, but pipeline gives the close price on 2022-05-16.

In my opinion, this is a error and should not be.

**Comment by MBounouar** [comment]
Without having actually tried your script, I noticed  the direct import and use of `exchange-calendars`. 
Please, don't import and use `exchange_calendars` directly, the package is **NOT** compatible with `zipline-reloaded` because it uses a different start date.
I am actually surprised that the code is actually running.
You have to instead import all the calendar functionalities like  'get_calendar'  from `zipline.utils.calendar_utils`

**Comment by vaa1234** [comment]
Here is a reproducible example zipline-reloaded install to clean conda env with AAL symbol:

```
from zipline.data.bundles import load
from zipline.pipeline import Pipeline
from zipline.pipeline.domain import US_EQUITIES
from zipline.pipeline.loaders import USEquityPricingLoader
from zipline.pipeline import SimplePipelineEngine
from zipline.api import order_target, record, symbol
from zipline.pipeline.data import USEquityPricing
from zipline.pipeline.filters import AllPresent, All, StaticAssets, StaticSids
import pandas as pd
from zipline.data.bundles import register, csvdir

bundle_data = load('quandl')

my_pipeline = Pipeline(
        columns = {
            'close': USEquityPricing.close.latest,
        },
        screen=( StaticSids([2]) ),
        # domain=US_EQUITIES
    )

pipeline_loader = USEquityPricingLoader.without_fx(bundle_data.equity_daily_bar_reader, bundle_data.adjustment_reader)

def choose_loader(column):
    return pipeline_loader

spe = SimplePipelineEngine(get_loader=choose_loader, asset_finder=bundle_data.asset_finder)

results = spe.run_pipeline(my_pipeline,
                           pd.Timestamp('2015-05-13', tz = 'utc'),
                           pd.Timestamp('2015-05-13', tz = 'utc'))
```

Result:

`2015-05-13 00:00:00+00:00 | Equity(2 [AAL]) | 48.85`

If we get data from this bundle on this date:

```
from zipline.data.data_portal import DataPortal
from zipline.data import bundles
from zipline.data.bundles import load, register
from zipline.utils.calendar_utils import get_calendar
import pandas as pd
from zipline.data import bundles

bundle_name = 'quandl'
ticker_name = "AAL"
end_date = pd.Timestamp('2015-05-13', tz='utc')
window=3
bundle_data = bundles.load(bundle_name)

data_por = DataPortal(bundle_data.asset_finder, 
                      get_calendar('XNYS'),
                      bundle_data.equity_daily_bar_reader.first_trading_day,
                      equity_minute_reader=bundle_data.equity_minute_bar_reader,
                      equity_daily_reader=bundle_data.equity_daily_bar_reader,
                      adjustment_reader=bundle_data.adjustment_reader)

sym = data_por.asset_finder.lookup_symbol(ticker_name, end_date)
data = data_por.get_history_window(assets=[sym],
                                   end_dt=end_date,
                                   bar_count=window,
                                   frequency='1d',
                                   data_frequency='daily',
                                   field='close')

```

Result:
```
2015-05-11 00:00:00+00:00	49.645
2015-05-12 00:00:00+00:00	48.850
2015-05-13 00:00:00+00:00	48.490
```

48.85 is price on 2015-05-12, but we request data in pipeline on 2015-05-13.

I used according to your advice `get_calendar` from `zipline.utils.calendar_utils` module.

**Comment by MBounouar** [comment]
https://github.com/stefan-jansen/zipline-reloaded/blob/b066f1cc7e463c64634911094e6215d0889477c9/src/zipline/pipeline/loaders/equity_pricing_loader.py#L74

This is actually an intended behavior, to avoid looking ahead your are only presented data from the previous session.

 " _load_adjusted_array is called with dates on which the user's algo
    will be shown data, which means we need to return the data that would
    be known at the **start** of each date. We assume that the latest
    data known on day N is the data from day (N - 1), so we shift all
    query dates back by a trading session."_

**Comment by vaa1234** [comment]
I got it, thanks for direction. I'll try to experiment with load_adjusted_array.

In my opinion, in real live trading mode, the behavior of pipeline should be different from the backtest.

For example, we run the algorithm today, May 20th. The pipeline will be executed on the date of the last trading session, May 19th. And the data according to this logic will be loaded on May 18. That is, we will operate with data with a delay of 1 day. Perhaps for some strategies this is not so critical, but, for example, for intraday strategies it is very critical. They won't work correctly.

Please correct me if I'm wrong.

**Comment by MBounouar** [comment]
This can become very confusing especially when using daily data.

The way I understand it, is that you cannot act on data that you haven't received yet, therefore the lag.
Supposing you want to trade at time `T` the only data that you have is coming from `T-1` that's the reasoning behind this shift.

**Comment by RiccaDS** [comment]
I can't help on this issue because I am working on backtests and don't know the live mode code. Backtests do have a shift  issue and in the end I think it is a little bug that will bother only some people with the result of not being able to use the first day of intraday data. It almost surely derives from the fact that with daily data(only 24h close/open prices) you cannot run a trading code without having at least the last closing price. So zipline was conceived to run tradings only when you provide a last closing price for the day before. However it seems that part of the code wasn't updated for intraday trading, for which the correct behavior is to run tradings when you have at least one minute closing price at the market opening. 
The last code I provided, which is a correction I made for this issue in backtests environment, needed some more work. Here is the updated code if needed(don't judge too bad, not a professional programmer here). Use this as lifetimes() function in assets.py.

```
     
        if isinstance(country_codes, str):
            raise TypeError(
                "Got string {!r} instead of an iterable of strings in "
                "AssetFinder.lifetimes.".format(country_codes),
            )

        # normalize to a cache-key so that we can memoize results.
        country_codes = frozenset(country_codes)

        lifetimes = self._asset_lifetimes.get(country_codes)
        if lifetimes is None:
            self._asset_lifetimes[
                country_codes
            ] = lifetimes = self._compute_asset_lifetimes(country_codes)

        raw_dates = as_column(dates.asi8)

        def todate1(tstamp):
             return np.array([datetime.utcfromtimestamp(tstamp[0] // 10**9).date()])
        def todate2(tstamp):
             return datetime.utcfromtimestamp(tstamp // 10**9).date()

        raw_dates_map = np.array(list(map(todate1,raw_dates)))
        start_map          = np.array(list(map(todate2,lifetimes.start))) 
        end_map           = np.array(list(map(todate2,lifetimes.end))) 

        if include_start_date:
            mask = start_map <= raw_dates_map
        else:
            mask = start_map < raw_dates_map

        mask &= raw_dates_map <= end_map

        return pd.DataFrame(mask, index=dates, columns=lifetimes.sid)

```

**Comment by stefan-jansen** [comment]
Thank you, please feel free to [open a PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) if you still feel this should be included so we can test the implications.
