### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NaTType'

### ISSUE THREAD

**Issue by javiersanser** [stefan-jansen/zipline-reloaded#101]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: (Linux 20.04.1-Ubuntu)
* Python Version: python 3.8.13 
* Python Bitness: 64
* How did you install Zipline: conda install -c conda-forge -c ranaroussi zipline-reloaded
* Python packages:
* 
Running zipline on Anaconda environment: conda 4.9.2

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
alembic                   1.7.7              pyhd8ed1ab_0    conda-forge
bcolz-zipline             1.2.4            py38hef53783_0    ml4t
blas                      1.0                         mkl  
bottleneck                1.3.4            py38hce1f21e_0  
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2021.10.8        py38h578d9bd_2    conda-forge
cffi                      1.15.0           py38hd667e15_1  
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.1.2            py38h578d9bd_0    conda-forge
cryptography              35.0.0           py38ha5dfef3_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
empyrical-reloaded        0.5.8                    py38_0    ml4t
greenlet                  1.1.1            py38h295c915_0  
h5py                      3.2.1           nompi_py38h9915d05_100    conda-forge
hdf5                      1.10.6          nompi_h3c11f04_101    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.3           py38h578d9bd_1    conda-forge
importlib_resources       5.7.1              pyhd8ed1ab_0    conda-forge
intel-openmp              2021.4.0          h06a4308_3561  
intervaltree              3.0.2                      py_0    conda-forge
iso3166                   2.0.2              pyhd8ed1ab_0    conda-forge
iso4217                   1.6.20180829               py_0    conda-forge
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               h14aa051_20    conda-forge
libgfortran4              7.5.0               h14aa051_20    conda-forge
libgomp                   9.3.0               h5101ec6_17  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libxml2                   2.9.12               h03d6c58_0  
libxslt                   1.1.34               hc22bd24_0  
logbook                   1.5.3                    py38_0    ml4t
lru-dict                  1.1.7            py38h497a2fe_0    conda-forge
lxml                      4.8.0            py38h1f438cf_0  
mako                      1.2.0              pyhd8ed1ab_1    conda-forge
markupsafe                2.0.1            py38h497a2fe_0    conda-forge
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py38h497a2fe_0    conda-forge
mkl_fft                   1.3.1            py38hd3c417c_0  
mkl_random                1.2.2            py38h1abd341_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
multitasking              0.0.9              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h7f8727e_2  
networkx                  2.3                        py_0    conda-forge
numexpr                   2.8.1            py38h6abb31d_0  
numpy                     1.21.5           py38he7a7128_1  
numpy-base                1.21.5           py38hf524024_1  
openssl                   1.1.1n               h7f8727e_0  
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.3.5                    pypi_0    pypi
pandas-datareader         0.10.0             pyh6c4a22f_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pip                       21.2.4           py38h06a4308_0  
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.8              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py38h578d9bd_5    conda-forge
python                    3.8.13               h12debd9_0  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-interface          1.6.0                      py_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
readline                  8.1.2                h7f8727e_1  
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
scipy                     1.7.3            py38hc147768_0  
setuptools                61.2.0           py38h06a4308_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlalchemy                1.4.13           py38h497a2fe_0    conda-forge
sqlite                    3.38.2               hc218d9a_0  
statsmodels               0.13.2           py38h7f8727e_0  
ta-lib                    0.4.21           py38hfeaa757_0    ml4t
tk                        8.6.11               h1ccaba5_0  
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
trading-calendars         2.1.1              pyhd3deb0d_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yfinance                  0.1.63                     py_0    ml4t
zipline-reloaded          2.0.0.post1      py38hef53783_0    ml4t
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h7f8727e_2  

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

When I try to make a zipline ingest -b quandl I get the following error:

Traceback (most recent call last):
  File "/home/../anaconda3/envs/zip38/bin/zipline", line 7, in <module>
    from zipline.__main__ import main
  File "/home/../anaconda3/envs/zip38/lib/python3.8/site-packages/zipline/__init__.py", line 21, in <module>
    from trading_calendars import get_calendar
  File "/home/../anaconda3/envs/zip38/lib/python3.8/site-packages/trading_calendars/__init__.py", line 16, in <module>
    from .trading_calendar import TradingCalendar
  File "/home/../anaconda3/envs/zip38/lib/python3.8/site-packages/trading_calendars/trading_calendar.py", line 33, in <module>
    from .calendar_helpers import (
  File "/home/../anaconda3/envs/zip38/lib/python3.8/site-packages/trading_calendars/calendar_helpers.py", line 6, in <module>
    NP_NAT = np.array([pd.NaT], dtype=np.int64)[0]
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NaTType'

* What did you expect to happen?

To make the bundle ingest without errors ;)

* What happened instead?

Typical python frustration XD

Here is how you can reproduce this issue on your machine:

## What steps have you taken to resolve this already?

I downgraded pandas to versión 1.3.5 by some google searching trying to solve the issue. Before that downgrade, pandas version was 1.4.2 with same error.
...

# Anything else?

Downgraded pandas all the way down to 1.2.4 with this error now:

ImportError: /.../anaconda3/envs/zip38/lib/python3.8/site-packages/h5py/defs.cpython-38-x86_64-linux-gnu.so: undefined symbol: H5Pset_fapl_ros3

I suppose in this case is due to pandas vs python version compatibility issues.

I have read this issue previously reported and closed with solution being reemplacing  the trading_calendar package  with the fork exchange_calendar packages, but perhaps I miss something and has not being able to fix this by now.
...

Sincerely,
Javier Sánchez

**Comment by MBounouar** [comment]
Apparently, you are not using the latest zipline-reloaded release.
pandas 1.3.5 should work however there is a catch with the exchange-calendars replacing the trading-calendars package.
 **I would advise to re-install from scratch to the latest release to get the dependencies under control**.

**Comment by javiersanser** [comment]
Thank you @MBounouar I reinstalled with :

`pip install zipline-reloaded `

instead of:

`conda install -c ml4t -c conda-forge -c ranaroussi zipline-reloaded`

And it's working. I don't know if the second method is not getting the latest version of the library, but the case is you are right. The latest command installed the versión 2.0.0 instead of 2.2.0. Perhaps it was my fault, but I don't know why. 

Thanks for your help.
