### ISSUE TITLE
Change to iso3166

### ISSUE THREAD

**Issue by pfin** [stefan-jansen/zipline-reloaded#114]
ISO3166 has been updated, “Turkey” changed to “Türkiye”.  This causes various things to break that relied on "TURKEY", setting ISO==2.02 works.  This is not necessarily a zipline problem, but can cause issues for fresh installs.  Posting here in case anyone else has the problem.  pip install iso3166==2.02 solves it

https://pypi.org/project/iso3166/
2.1.0 - July 11, 2022
-Updated entries
---“Turkey” changed to “Türkiye”

**Comment by casras111** [comment]
works (version number 2.0.2)

**Comment by RichardDale** [comment]
Slight typo... it sohuld be:

` pip install iso3166==2.0.2`

**Comment by RichardDale** [comment]
For completeness, this is how I create a new environment, complete with forcing the iso3166 install to 2.0.2:

```
conda create -y -n zip38 python=3.8
conda activate zip38
conda install -y -c conda-forge mamba
mamba install -y -c ml4t -c conda-forge -c ranaroussi pandas==1.3.5 numpy==1.22.4  zipline-reloaded pyfolio-reloaded iso3166==2.0.2
mamba install -y -c conda-forge jupyter
if not exist %HOMEPATH%\.zipline mkdir %HOMEPATH%\.zipline
if not exist %HOMEPATH%\.zipline\extension.py copy /b NUL > %HOMEPATH%\.zipline\extension.py

```

**Comment by joshua-xia** [comment]
Is there plan to fix this issue? or we have to downgrade the iso3166 to 2.0.2?

**Comment by agcap1** [comment]
pip install iso3166==2.0.2     solved the issue for me .  python 3.8.
