### ISSUE TITLE
KeyError: 'TURKEY' when importing Zipline with Python v3.7 and v3.8

### ISSUE THREAD

**Issue by HelmieCapital** [stefan-jansen/zipline-reloaded#116]
### Discussed in https://github.com/stefan-jansen/zipline-reloaded/discussions/115

<div type='discussions-op-text'>

<sup>Originally posted by **HelmieCapital** July 14, 2022</sup>
Good day,

There seems to be an inexplicable key error when importing Zipline.

Can someone please explain what the issue is ?

The import suddenly stopped working in my project since last night.

Here is the traceback:

Traceback (most recent call last)
[<ipython-input-1-ab8bff6e5ffb>](https://localhost:8080/#) in <module>()
----> 1 import zipline

9 frames
[/usr/local/lib/python3.7/dist-packages/zipline/__init__.py](https://localhost:8080/#) in <module>()
     27 from .utils.numpy_utils import numpy_version
     28 from .utils.pandas_utils import new_pandas
---> 29 from .utils.run_algo import run_algorithm
     30 
     31 # These need to happen after the other imports.

[/usr/local/lib/python3.7/dist-packages/zipline/utils/run_algo.py](https://localhost:8080/#) in <module>()
     22 from zipline.finance import metrics
     23 from zipline.finance.trading import SimulationParameters
---> 24 from zipline.pipeline.data import USEquityPricing
     25 from zipline.pipeline.loaders import USEquityPricingLoader
     26 

[/usr/local/lib/python3.7/dist-packages/zipline/pipeline/__init__.py](https://localhost:8080/#) in <module>()
----> 1 from .classifiers import Classifier, CustomClassifier
      2 from .domain import Domain
      3 from .factors import Factor, CustomFactor
      4 from .filters import Filter, CustomFilter
      5 from .term import Term, LoadableTerm, ComputableTerm

[/usr/local/lib/python3.7/dist-packages/zipline/pipeline/classifiers/__init__.py](https://localhost:8080/#) in <module>()
----> 1 from .classifier import (
      2     Classifier,
      3     CustomClassifier,
      4     Quantiles,
      5     Everything,

[/usr/local/lib/python3.7/dist-packages/zipline/pipeline/classifiers/classifier.py](https://localhost:8080/#) in <module>()
     20 )
     21 from zipline.pipeline.sentinels import NotSpecified
---> 22 from zipline.pipeline.term import ComputableTerm
     23 from zipline.utils.compat import unicode
     24 from zipline.utils.input_validation import expect_types, expect_dtypes

[/usr/local/lib/python3.7/dist-packages/zipline/pipeline/term.py](https://localhost:8080/#) in <module>()
     43 )
     44 
---> 45 from .domain import Domain, GENERIC, infer_domain
     46 from .downsample_helpers import expect_downsample_frequency
     47 from .sentinels import NotSpecified

[/usr/local/lib/python3.7/dist-packages/zipline/pipeline/domain.py](https://localhost:8080/#) in <module>()
     25 from zipline.utils.calendar_utils import get_calendar
     26 
---> 27 from zipline.country import CountryCode
     28 from zipline.utils.formatting import bulleted_list
     29 from zipline.utils.input_validation import expect_types, optional

[/usr/local/lib/python3.7/dist-packages/zipline/country.py](https://localhost:8080/#) in <module>()
      8 
      9 
---> 10 class CountryCode(object):
     11     """A simple namespace of iso3166 alpha2 country codes."""
     12 

[/usr/local/lib/python3.7/dist-packages/zipline/country.py](https://localhost:8080/#) in CountryCode()
     53     TAIWAN = code("TAIWAN, PROVINCE OF CHINA")
     54     THAILAND = code("THAILAND")
---> 55     TURKEY = code("TURKEY")
     56     UNITED_KINGDOM = code("UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND")
     57     UNITED_STATES = code("UNITED STATES OF AMERICA")

[/usr/local/lib/python3.7/dist-packages/zipline/country.py](https://localhost:8080/#) in code(name)
      5 
      6 def code(name):
----> 7     return countries_by_name[name].alpha2
      8 
      9 

KeyError: 'TURKEY'

</div>

**Comment by RichardDale** [comment]
See #114 - it appears that the key used for the country Turkey has changed.

A workaround is provided there to show how to install an earlier version.

In summary:
` pip install iso3166==2.02`

**Comment by monstaaa** [comment]
Another workaround is to directly change the `country.py` file

Change to this value.

`TURKEY = code("TÜRKIYE")`

**Comment by HelmieCapital** [comment]
Hi there,

Thanks guys for responding

Yes, I did that last night but forgot to post the solution here.

**Both solutions work perfectly fine.**

Will close the issue as resolved
