### ISSUE TITLE
CI Tests is broken

### ISSUE THREAD

**Issue by MBounouar** [stefan-jansen/zipline-reloaded#122]
Dear Zipline Maintainers,

# Environment
github CI tests

# Description of Issue
The tests are  failing for Python >=3.8
with error 
  `RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
  `
the CI workflow would probably need to be rewritten. I suspect an issue with how the environment is built and TA-Lib compiled

## Reproduction Steps
Executing CI Tests on github

**Comment by stefan-jansen** [comment]
Should be addressed by latest update.
