### ISSUE TITLE
OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1677-09-21 00:00:00

### ISSUE THREAD

**Issue by zhangjianliang1** [stefan-jansen/zipline-reloaded#127]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

</details>

Now that you know a little about me, let me tell you about the issue I am
having:
I ingest my chinese stock data and use it to backtesting with pipeline factor.But when i use run_algorithm there is the error:
OutOfBoundsDatetime                       Traceback (most recent call last)
~\AppData\Local\Temp\tmp24i55k5_\ipykernel_13180\3170537094.py in <module>
      7                         data_frequency='daily',
      8                         bundle='cnstock',
----> 9                         custom_loader=signal_loader)# need to modify zipline
     10 
     11 print('Duration: {:.2f}s'.format(time() - start))

c:\Users\zjlqaq\anaconda3\envs\zipline_env2\lib\site-packages\zipline\utils\run_algo.py in run_algorithm(start, end, initialize, capital_base, handle_data, before_trading_start, analyze, data_frequency, bundle, bundle_timestamp, trading_calendar, metrics_set, benchmark_returns, default_extension, extensions, strict_extensions, environ, custom_loader, blotter)
    417         blotter=blotter,
    418         custom_loader=custom_loader,
--> 419         benchmark_spec=benchmark_spec,
    420     )
    421 

c:\Users\zjlqaq\anaconda3\envs\zipline_env2\lib\site-packages\zipline\utils\run_algo.py in _run(handle_data, initialize, before_trading_start, analyze, algofile, algotext, defines, data_frequency, capital_base, bundle, bundle_timestamp, start, end, output, trading_calendar, print_algo, metrics_set, local_namespace, environ, blotter, custom_loader, benchmark_spec)
    223             else {
    224                 "algo_filename": getattr(algofile, "name", "<algorithm>"),
--> 225                 "script": algotext,
    226             },
    227         ).run()

c:\Users\zjlqaq\anaconda3\envs\zipline_env2\lib\site-packages\zipline\algorithm.py in run(self, data_portal)
    621         try:
...
c:\Users\zjlqaq\anaconda3\envs\zipline_env2\lib\site-packages\pandas\_libs\tslibs\conversion.pyx in pandas._libs.tslibs.conversion.convert_datetime_to_tsobject()

c:\Users\zjlqaq\anaconda3\envs\zipline_env2\lib\site-packages\pandas\_libs\tslibs\np_datetime.pyx in pandas._libs.tslibs.np_datetime.check_dts_bounds()

OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1677-09-21 00:00:00

I find my raw data have no timestamp: 1677-09-21 00:00:00 and error timestamp,and i can't find the error.If anyone can solve or there is any api to see my bundle data timestamp?

Here is how you can reproduce this issue on your machine:

**Comment by stefan-jansen** [comment]
It's hard to say what's going on without being able to replicate the issue, which in turn would likely require at least some of the source data. 

However, data without time stamp is odd because how would a price series be organized otherwise?

**Comment by stefan-jansen** [comment]
Closing for now due to lack of activity.
