### ISSUE TITLE
bcolz silent failure causes failed ingest on Mac M1 running Parallels/Windows environment

### ISSUE THREAD

**Issue by RichardDale** [stefan-jansen/zipline-reloaded#128]
This is not really a Zipline issue, but is most likely related to x64 emulation issues.  I've posted this as an issue here, so that others might find it.

Symptom: Ingests fail on certain bundle definitions - there is no error message - it just stops.  
Enviornment: Mac M1 CPU, running Parallels and Windows 11.  All platforms are at latest versions.

This appears to completely crash Python - SILENTLY!! - for an unknown reason.  We couldn't even trap this in a try/except block. When we dug further (Windows Event Viewer) we found that the actual fault lies within:
bcolz/carray_ext.cp38-win_amd64.pyd

Bcolz a package that performs compression, which is used by Zipline to reduce disk storage.  It is is highly optimized for particular CPUs and uses various low-level/machine code to improvement performance.

On a hunch, I went to see if there had been any newer bcolz released:
https://anaconda.org/conda-forge/bcolz/files

There was one dated about a month ago in cf-staging.
 
So, I tried installing it with:
`conda install -c cf-staging bcolz`

This solved the issue on both our test system here (Mac M1 Mini) and a client's PC Mac M1 Macbook Pro.

Hope this helps someone else out.  It took me a few hours to get to this point.

Cheers,
Richard.

**Comment by stefan-jansen** [comment]
I''ve updated [bcolz-zipline](https://github.com/stefan-jansen/bcolz-zipline) with a release coming shortly, and capped the NumPy version to < 1.23 before I can figure out how to address how the changes in that release break bcolz.
