### ISSUE TITLE
Possible Wrong Stock Price in Zipline Tutorial

### ISSUE THREAD

**Issue by wuyuhang1995** [stefan-jansen/zipline-reloaded#138]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?

I have gone through the tutorial for zipline. However, I found that in this link: 
https://zipline.ml4trading.io/beginner-tutorial.html?highlight=stock%20price
the plot for AAPL stock price is not correct. If you check the stock price for a particular day on the website, it is around 4 times different as the data shown in the plot. Additionally, I have got the same plot.  Can I know how to fix it?

* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by stefan-jansen** [comment]
This reflects of the [4:1 stock split](https://investor.apple.com/faq/default.aspx) in 2020, several years after the plot, not know at the time but of course included in today's (backward-adjusted) price series.
