### ISSUE TITLE
TA-Lib version 0.4.25 fails to import

### ISSUE THREAD

**Issue by MBounouar** [stefan-jansen/zipline-reloaded#142]
The latest **TA-Lib 0.4.25**  can create issues 
` RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf`

`from ._ta_lib import ( talib/_func.pxi:15: in init talib._ta_lib ??? __init__.pxd:944: in numpy.import_array ??? E ImportError: numpy.core.multiarray failed to import
`

**_Downgrading_** to  version **0.4.24** solved the problem.

> Edit:
Actually this isn't as simple as that.
The CI fails for similar reasons, but downgrading won't solve the issue. I can't pinpoint where the issue is but it seems that there is an issue when installing/building the wheel for TA-Lib. Perhaps numpy installation order and version

**Comment by stefan-jansen** [comment]
Installing from source (latest) or 0.4.24 after installing Zipline works, incl. on CI. TA-Lib includes compiled extensions and has no wheels hence the compatibility problems. Latest on main and coming release should fix this.
