### ISSUE TITLE
Import Error LOAD while ingesting custom data in zipline

### ISSUE THREAD

**Issue by KrishnaRachh** [stefan-jansen/zipline-reloaded#150]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System:  windows11
* Python Version: python 3.8
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Zipline: ml4t
* Python packages: `$ pip freeze` or `$ conda list`
* alabaster                 0.7.12             pyhd3eb1b0_0
alembic                   1.8.1              pyhd8ed1ab_0    conda-forge
anyio                     3.5.0            py38haa95532_0
argon2-cffi               21.3.0             pyhd3eb1b0_0
argon2-cffi-bindings      21.2.0           py38h2bbff1b_0
arrow                     1.2.3            py38haa95532_0
astroid                   2.11.7           py38haa95532_0
atomicwrites              1.4.0                      py_0
attrs                     22.1.0           py38haa95532_0
autopep8                  1.6.0              pyhd3eb1b0_1
babel                     2.9.1              pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
bcolz-zipline             1.2.6            py38he6999da_0    ml4t
bcrypt                    3.2.0            py38h2bbff1b_1
beautifulsoup4            4.11.1           py38haa95532_0
binaryornot               0.4.4              pyhd3eb1b0_1
black                     22.6.0           py38haa95532_0
blas                      1.0                         mkl
bleach                    4.1.0              pyhd3eb1b0_0
blosc                     1.21.1               hcbbf2c4_0    conda-forge
bottleneck                1.3.5            py38hbdcd294_0    conda-forge
brotli                    1.0.9                h2bbff1b_7
brotli-bin                1.0.9                h2bbff1b_7
brotlipy                  0.7.0           py38h294d835_1004    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.10.11           haa95532_0
certifi                   2022.9.24        py38haa95532_0
cffi                      1.15.1           py38hd8c33c5_0    conda-forge
chardet                   4.0.0           py38haa95532_1003
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3           win_pyhd8ed1ab_2    conda-forge
cloudpickle               2.0.0              pyhd3eb1b0_0
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
console_shortcut          0.1.1                         4
cookiecutter              1.7.3              pyhd3eb1b0_0
cryptography              3.4.8            py38hb7941b4_1    conda-forge
cycler                    0.11.0             pyhd3eb1b0_0
debugpy                   1.5.1            py38hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
diff-match-patch          20200713           pyhd3eb1b0_0
dill                      0.3.6            py38haa95532_0
docutils                  0.18.1           py38haa95532_3
empyrical-reloaded        0.5.8                    py38_0    ml4t
entrypoints               0.4              py38haa95532_0
exchange-calendars        3.3                      py38_0    ml4t
flake8                    4.0.1              pyhd3eb1b0_1
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.12.1               ha860e81_0
glib                      2.69.1               h5dc1a3c_2
greenlet                  1.1.1            py38hd77b12b_0
gst-plugins-base          1.18.5               h9e645db_0
gstreamer                 1.18.5               hd78058f_0
h5py                      2.10.0           py38h5e291fa_0
hdf5                      1.10.4          nompi_hcc15c50_1106    conda-forge
icu                       58.2                 ha925a31_3
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1            py38haa95532_0
importlib-metadata        4.11.3           py38haa95532_0
importlib_metadata        4.11.3               hd3eb1b0_0
importlib_resources       5.10.0             pyhd8ed1ab_0    conda-forge
inflection                0.5.1            py38haa95532_0
intel-openmp              2022.1.0          h57928b3_3787    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 6.15.2           py38haa95532_0
ipython                   7.31.1           py38haa95532_1
ipython_genutils          0.2.0              pyhd3eb1b0_1
iso3166                   2.0.2                    pypi_0    pypi
iso4217                   1.9.20220401       pyhd8ed1ab_0    conda-forge
isort                     5.9.3              pyhd3eb1b0_0
jedi                      0.18.1           py38haa95532_1
jellyfish                 0.9.0            py38h2bbff1b_0
jinja2                    3.1.2            py38haa95532_0
jinja2-time               0.2.0              pyhd3eb1b0_3
jpeg                      9e                   h2bbff1b_0
jsonschema                4.16.0           py38haa95532_0
jupyter_client            7.4.7            py38haa95532_0
jupyter_core              4.11.2           py38haa95532_0
jupyter_server            1.18.1           py38haa95532_0
jupyterlab_pygments       0.1.2                      py_0
keyring                   23.4.0           py38haa95532_0
kiwisolver                1.4.2            py38hd77b12b_0
korean_lunar_calendar     0.3.1              pyhd8ed1ab_0    conda-forge
lazy-object-proxy         1.6.0            py38h2bbff1b_0
lerc                      3.0                  hd77b12b_0
libblas                   3.9.0              12_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libcblas                  3.9.0              12_win64_mkl    conda-forge
libclang                  12.0.0          default_h627e005_2
libdeflate                1.8                  h2bbff1b_5
libffi                    3.4.2                hd77b12b_6
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0              12_win64_mkl    conda-forge
libogg                    1.3.5                h2bbff1b_1
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h6c2663c_0
libtiff                   4.4.0                h8a3f274_2
libvorbis                 1.3.7                he774522_0
libwebp                   1.2.4                h2bbff1b_0
libwebp-base              1.2.4                h2bbff1b_0
libxml2                   2.9.14               h0ad7f3c_0
libxslt                   1.1.35               h2bbff1b_0
logbook                   1.5.3                    py38_0    ml4t
lru-dict                  1.1.8            py38h294d835_0    conda-forge
lxml                      4.9.1            py38h294d835_0    conda-forge
lz4-c                     1.9.3                h2bbff1b_1
lzo                       2.10              he774522_1000    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mako                      1.2.4              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1            py38h294d835_1    conda-forge
matplotlib                3.5.3            py38haa95532_0
matplotlib-base           3.5.3            py38hd77b12b_0
matplotlib-inline         0.1.6            py38haa95532_0
mccabe                    0.7.0              pyhd3eb1b0_0
mistune                   0.8.4           py38he774522_1000
mkl                       2021.4.0           h0e2418a_729    conda-forge
mkl-service               2.4.0            py38h4f8af0f_0    conda-forge
mock                      4.0.3              pyhd8ed1ab_4    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
multitasking              0.0.9              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4                      py_0
mypy_extensions           0.4.3            py38haa95532_1
nb_conda                  2.2.1                    py38_1
nb_conda_kernels          2.3.1            py38haa95532_0
nbclassic                 0.4.8            py38haa95532_0
nbclient                  0.5.13           py38haa95532_0
nbconvert                 6.5.4            py38haa95532_0
nbformat                  5.5.0            py38haa95532_0
nest-asyncio              1.5.5            py38haa95532_0
networkx                  2.8.8              pyhd8ed1ab_0    conda-forge
notebook                  6.5.2            py38haa95532_0
notebook-shim             0.2.2            py38haa95532_0
numexpr                   2.8.4            py38h5b0cc5e_0
numpy                     1.22.3           py38h1d2777f_2    conda-forge
numpydoc                  1.5.0            py38haa95532_0
openssl                   1.1.1s               h2bbff1b_0
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.4            py38hd77b12b_0
pandas-datareader         0.10.0             pyh6c4a22f_0    conda-forge
pandocfilters             1.5.0              pyhd3eb1b0_0
paramiko                  2.8.1              pyhd3eb1b0_0
parso                     0.8.3              pyhd3eb1b0_0
pathspec                  0.9.0            py38haa95532_0
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 hd77b12b_0
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    9.2.0            py38hdc2b20a_1
pip                       22.2.2           py38haa95532_0
pkgutil-resolve-name      1.3.10           py38haa95532_0
platformdirs              2.5.2            py38haa95532_0
pluggy                    1.0.0            py38haa95532_1
ply                       3.11                     py38_0
powershell_shortcut       0.0.1                         3
poyo                      0.5.0              pyhd3eb1b0_0
prometheus_client         0.14.1           py38haa95532_0
prompt-toolkit            3.0.20             pyhd3eb1b0_0
psutil                    5.9.0            py38h2bbff1b_0
ptyprocess                0.7.0              pyhd3eb1b0_2
pycodestyle               2.8.0              pyhd3eb1b0_0
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydocstyle                6.1.1              pyhd3eb1b0_0
pyflakes                  2.4.0              pyhd3eb1b0_0
pygments                  2.11.2             pyhd3eb1b0_0
pylint                    2.14.5           py38haa95532_0
pyls-spyder               0.4.0              pyhd3eb1b0_0
pyluach                   2.0.2              pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0            py38h8cc25b3_0
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7           py38hd77b12b_0
pyqt5-sip                 12.11.0          py38hd77b12b_0
pyqtwebengine             5.15.7           py38hd77b12b_0
pyreadline                2.1             py38haa244fe_1007    conda-forge
pyrsistent                0.18.0           py38h196d8e1_0
pysocks                   1.7.1              pyh0701188_6    conda-forge
pytables                  3.6.1            py38ha5be198_0
python                    3.8.0                hff0d562_2
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.2           py38haa95532_0
python-interface          1.6.0                      py_0    conda-forge
python-lsp-black          1.2.1            py38haa95532_0
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0
python-lsp-server         1.5.0            py38haa95532_0
python-slugify            5.0.2              pyhd3eb1b0_0
python_abi                3.8                      2_cp38    conda-forge
pytz                      2022.6             pyhd8ed1ab_0    conda-forge
pywin32                   302              py38h2bbff1b_2
pywin32-ctypes            0.2.0                 py38_1000
pywinpty                  2.0.2            py38h5da7b33_0
pyyaml                    6.0              py38h2bbff1b_1
pyzmq                     23.2.0           py38hd77b12b_0
qdarkstyle                3.0.2              pyhd3eb1b0_0
qstylizer                 0.1.10             pyhd3eb1b0_0
qt-main                   5.15.2               he8e5bd7_7
qt-webengine              5.15.9               hb9a9bb5_4
qtawesome                 1.0.3              pyhd3eb1b0_0
qtconsole                 5.3.2            py38haa95532_0
qtpy                      2.2.0            py38haa95532_0
qtwebkit                  5.212                h3ad3cdb_4
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
rope                      0.22.0             pyhd3eb1b0_0
rtree                     0.9.7            py38h2eaa2aa_1
scipy                     1.8.1            py38h4990095_2    conda-forge
send2trash                1.8.0              pyhd3eb1b0_1
setuptools                65.5.0           py38haa95532_0
sip                       6.6.2            py38hd77b12b_0
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                h82413e6_1    conda-forge
sniffio                   1.2.0            py38haa95532_1
snowballstemmer           2.2.0              pyhd3eb1b0_0
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1      py38haa95532_0
sphinx                    5.0.2            py38haa95532_0
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0
spyder                    5.3.3            py38haa95532_0
spyder-kernels            2.3.3            py38haa95532_0
sqlalchemy                1.4.13           py38h294d835_0    conda-forge
sqlite                    3.40.0               h2bbff1b_0
statsmodels               0.13.2           py38h2bbff1b_0
ta-lib                    0.4.25           py38h5685391_0    ml4t
tbb                       2021.6.0             h59b6b97_0
terminado                 0.13.1           py38haa95532_0
text-unidecode            1.3                pyhd3eb1b0_0
textdistance              4.2.1              pyhd3eb1b0_0
three-merge               0.1.1              pyhd3eb1b0_0
tinycss                   0.4             pyhd3eb1b0_1002
tinycss2                  1.2.1            py38haa95532_0
tk                        8.6.12               h2bbff1b_0
toml                      0.10.2             pyhd3eb1b0_0
tomli                     2.0.1            py38haa95532_0
tomlkit                   0.11.1           py38haa95532_0
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2              py38h2bbff1b_0
trading-calendars         2.1.1              pyhd3deb0d_0    conda-forge
traitlets                 5.1.1              pyhd3eb1b0_0
typing-extensions         4.3.0            py38haa95532_0
typing_extensions         4.3.0            py38haa95532_0
ujson                     5.4.0            py38hd77b12b_0
unidecode                 1.2.0              pyhd3eb1b0_0
urllib3                   1.26.13            pyhd8ed1ab_0    conda-forge
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
watchdog                  2.1.6            py38haa95532_0
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1                    py38_1
websocket-client          0.58.0           py38haa95532_4
whatthepatch              1.0.2            py38haa95532_0
wheel                     0.37.1             pyhd3eb1b0_0
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
wincertstore              0.2              py38haa95532_2
winpty                    0.4.3                         4
wrapt                     1.14.1           py38h2bbff1b_0
xz                        5.2.6                h8cc25b3_0
yaml                      0.2.5                he774522_0
yapf                      0.31.0             pyhd3eb1b0_0
yfinance                  0.1.63                     py_0    ml4t
zeromq                    4.3.4                hd77b12b_0
zipline-reloaded          2.2.0            py38he6999da_0    ml4t
zipp                      3.11.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.2                h19a0ad4_0

</details>

Now that you know a little about me, let me tell you about the issue I am
having:
- I am facing error while ingesting data bundle. 
- this is how my extension.py looks like : 
 import pandas as pd

from zipline.data.bundles import register
from zipline.data.bundles.csvdir import csvdir_equities

start_session = pd.Timestamp('2017-1-2', tz='utc')
end_session = pd.Timestamp('2022-6-30', tz='utc')

# register the bundle
register(
    'abcdata',  
    csvdir_equities(['daily'],"C:\\Users\\krkoo\\anaconda3\\envs\\env_zip\\Lib\\site-packages\\zipline\\data\\bundles\\zipline_form_data"),
    calendar_name='XBOM',  
    start_session=start_session,
    end_session=end_session
)

when i run this command in cmd: 
         zipline ingest -b abcdata
I get error as follows:
__Traceback (most recent call last):
  File "C:\Users\krkoo\anaconda3\envs\env_zip\Scripts\zipline-script.py", line 6, in <module>
    from zipline.__main__ import main
  File "C:\Users\krkoo\anaconda3\envs\env_zip\lib\site-packages\zipline\__init__.py", line 29, in <module>
    from .utils.run_algo import run_algorithm
  File "C:\Users\krkoo\anaconda3\envs\env_zip\lib\site-packages\zipline\utils\run_algo.py", line 28, in <module>
    from zipline.extensions import load
ImportError: cannot import name 'load' from 'zipline.extensions' (C:\Users\krkoo\anaconda3\envs\env_zip\lib\site-packages\zipline\extensions.py)__

## What steps have you taken to resolve this already?
I have tried tweaking with extions file and csvdir file but nothing is solving this issue.. 

Sincerely,
Krishna Rachh

Waiting for a reply thanks!!

**Comment by stefan-jansen** [comment]
Please see examples on creating custom bundles [here](https://github.com/stefan-jansen/machine-learning-for-trading/tree/main/08_ml4t_workflow/04_ml4t_workflow_with_zipline/01_custom_bundles).

Closing for now but feel free to reopen in case these don't address your issue.
