### ISSUE TITLE
Mamba/Conda installs 2.0.0.rc4 instead of 2.0.0.post1

### ISSUE THREAD

**Issue by RichardDale** [stefan-jansen/zipline-reloaded#16]
Hi Stefan,

Nice work on packaging up 2.0.0.post1 - I've seen the recent commits and it looks like a complex task juggling all those items.

However, using either conda or mamba installs 2.0.0.rc4 instead of 2.0.0.post1 

Perhaps you need to change the versioning convention?  2.0.1 might be better?

## Reproduction Steps

conda create -n zip38 python=3.8
conda activate zip38
conda install -c ml4t -c conda-forge 

conda create -n zip38 python=3.8
conda activate zip38
conda install -y -c conda-forge mamba
mamba install -c ml4t -c conda-forge 

Cheers,
Richard.

**Comment by RichardDale** [comment]
Woarkaround to install this specific version:

mamba install -c ml4t -c conda-forge -c ranaroussi zipline-reloaded=2.0.0.post1 

(note the -c ranaroussi is required because of the issue posted in: #17 )

**Comment by stefan-jansen** [comment]
Updated the instructions - see other issue. 

On Windows and Ubuntu with Python 3.7/3.8, conda installs 2.0.0.post1; this may have been a matter of updating `conda` in the `base` environment?

**Comment by EcoFin** [comment]
Just by the way, on an existing install of 2.0.0rc4 (Win10x64) the  conda instruction didn't do anything:
 
    conda install -c ml4t -c conda-forge -c ranaroussi zipline-reloaded

The mamba one, however, worked as expected:

    mamba install -c ml4t -c conda-forge -c ranaroussi zipline-reloaded=2.0.0.post1

**Comment by stefan-jansen** [comment]
`conda install` unfortunately has [many issues](https://github.com/conda/conda/issues/8051). Hence the recommendation to use `mamba install ` instead.

**Comment by RichardDale** [comment]
FYI, can confirm this resolved.  Must have been an early dependency gotcha that got fixed along the way.
