### ISSUE TITLE
Problem ingesting csv data using Jupyter Lab

### ISSUE THREAD

**Issue by thetehtrader** [stefan-jansen/zipline-reloaded#162]
Dear Zipline Maintainers,

I hope you do not get bored answering a beginner's question; but I am really struggling making zipline work during the previous days.... I have finally managed to install & run it via jupyter lab & conda; but I cannot manage to ingest a simple csv file:

<details>
Operating System: (Windows)
numpy==1.22.3
pandas==1.4.4
Python 3.8.15

Excel File Location and data:
<C:\Users\x\Documents\csvdir\daily\META.csv>
date,open,high,low,close,volume,dividend,split
2012-01-03,58.48,58.92,58.42,58.74,75555200,0,1
2012-01-04,58.57,59.24,58.46,59.06,65005500,0,1
2012-01-05,59.27,59.79,58.95,59.71,67817400,0,1
2012-01-06,59.96,60.39,59.88,60.34,79573200,0,1
2012-01-09,60.78,61.1,60.19,60.24,98506100,0,1
2012-01-10,60.84,60.85,60.21,60.46,64549100,0,1
2012-01-11,60.38,60.4,59.9,60.36,53771200,0,1

Zipline Folder:
C:\Users\x\ .zipline

Now that you know a little about me, let me tell you about the issue I am
having:

I first run this code in Jupyter lab:

import numpy as np
import pandas as pd
from zipline.examples import buyapple
from zipline.api import order, record, symbol
from platform import python_version

%load_ext zipline
from zipline.data.bundles import register
from zipline.data.bundles.csvdir import csvdir_equities

start_session = pd.Timestamp('2012-01-03', tz='utc')
end_session = pd.Timestamp('2012-01-11', tz='utc')

register(
    'custom1',
    csvdir_equities(
        ["daily"], 
        '/Users/x/Documents/csvdir'),
    start_session = start_session,
    end_session = end_session
)

After running the above codes I get this feedback: <bound method CSVDIRBundle.ingest of <zipline.data.bundles.csvdir.CSVDIRBundle object at 0x0000016A26CFD970>>
So, I thought that the custom1 is now registered and ready to be ingested.... 
I tried to ingest the data using anaconda powershell prompt; so I closed Jupyter lab; & opened a new powershell prompt; activated the relevant environment and typed:

(clone_zipline) PS C:\Users\x> zipline ingest -b custom1

I got the error:  
Error: No bundle registered with the name 'custom1'

Any help will be highly appreciated. 
Thanks & Greetings

**Comment by stefan-jansen** [comment]
How about running 
```
!zipline ingest -b custom1
```
in jupyter lab?

**Comment by thetehtrader** [comment]
then I get this error:
'zipline' is not recognized as an internal or external command, operable program or batch file.

**Comment by jasonstrimpel** [comment]
Try this at the command line:

`zipline bundles`

That lists all your bundles. If you don't see the one you created, Zipline does not know about it.

The bundle system requires "registering" them in memory.

When you define your custom bundle, make sure it's registered. You can see an example [here](https://github.com/stefan-jansen/zipline-reloaded/blob/ef7cfef94e2db9b11ebcc7ebb5e49d3c654e1f2d/src/zipline/data/bundles/quandl.py#L158).

Here are the steps to register the bundle from the documentation:

Once you have your data in the correct format, you can edit your `extension.py` file in `~/.zipline/extension.py` and import the csvdir bundle, along with pandas.

```
import pandas as pd

from zipline.data.bundles import register
from zipline.data.bundles.csvdir import csvdir_equities
```

Change `from zipline.data.bundles.csvdir import csvdir_equities` to point to the Python file you created with your custom bundle.

We’ll then want to specify the start and end sessions of our bundle data:

```
start_session = pd.Timestamp('2016-1-1', tz='utc')
end_session = pd.Timestamp('2018-1-1', tz='utc')
```

And then we can register() our bundle, and pass the location of the directory in which our .csv files exist:

```
register(
    'custom-csvdir-bundle',
    csvdir_equities(
        ['daily'],
        '/path/to/your/csvs',
    ),
    calendar_name='NYSE', # US equities
    start_session=start_session,
    end_session=end_session
)
```

To finally ingest our data, we can run:

```
$ zipline ingest -b custom-csvdir-bundle
```

Link to docs is [here](https://zipline-trader.readthedocs.io/en/latest/bundles.html) (scroll to the end).

**Comment by thetehtrader** [comment]
Thank you Jason!
I followed your instructions & did everything this time in anaconda PowerShell (no jupyter lab) by saving the codes in extension.py (in .zipline folder), setting the current directory to this folder & running .py in PowerShell using python extension.py command.
I somehow managed to ingest the data. & load them. No idea why Jupyter lab does not work. Even after digesting the data bundle, jupyter lab does not show the ingested bundle (although everything works fine in anaconda PowerShell & the bundle is there too).
Am I missing something here? Should I set any specific path or directory or Zipline Root in jupyter lab? I am a beginner & the probability that I have problems with defined path, directory or Zipline Root can be high ;)
Any advice?

Greetings

**Comment by jasonstrimpel** [comment]
I’m not in front of a laptop but the magics should be set up automatically with the install. Make sure your Jupyter Notebook is launching from the same environment that you installed Zipline in. This gets a little complicated if you’re just getting started.On Jan 29, 2023, at 12:15, thetehtrader ***@***.***> wrote:﻿
Thank you Jason!
I followed your instructions & did everything this time in anaconda PowerShell (no jupyter lab) by saving the codes in extension.py (in .zipline folder), setting the current directory to this folder & running .py in PowerShell using python extension.py command.
I somehow managed to ingest the data. & load them. No idea why Jupyter lab does not work. Even after digesting the data bundle, jupyter lab does not show the ingested bundle (although everything works fine in anaconda PowerShell & the bundle is there too).
Am I missing something here? Should I set any specific path or directory or Zipline Root in jupyter lab? I am a beginner & the probability that I have problems with defined path, directory or Zipline Root can be high ;)
Any advice?
Greetings

**Comment by thetehtrader** [comment]
my jupyter lab is launching from base .... I made another environment for zipline package and connected it to jupyter lab via ipykernel. Can that be the reason?

**Comment by stefan-jansen** [comment]
See also [here](https://github.com/stefan-jansen/machine-learning-for-trading/tree/main/08_ml4t_workflow/04_ml4t_workflow_with_zipline/01_custom_bundles) for custom bundle registration / ingestion.

**Comment by jasonstrimpel** [comment]
You have to run Jupyter from the same environment you installed Zipline (base or otherwise).On Jan 29, 2023, at 14:08, thetehtrader ***@***.***> wrote:﻿
my jupyter lab is launching from base .... I made another environment for zipline package and connected it to jupyter lab via ipykernel. Can that be the reason?

**Comment by thetehtrader** [comment]
ok, I installed the jupyterlab directly in the zipline environment & called it from there. I saw some improvements; for instance the command, which Stefan wrote above (!zipline ingest -b custom1) works again in jupyter lab. 

I, however, do not understand, why the codes written below do not work in jupyter lab directly but in extension.py. Let me explain:

import os
os.getcwd()

os.chdir('C:\\Users\\x\\.zipline')
os.getcwd()

import numpy as np
import pandas as pd
from zipline.examples import buyapple
from zipline.api import order, record, symbol

%load_ext zipline
from zipline.data.bundles import register
from zipline.data.bundles.csvdir import csvdir_equities

from zipline.data.bundles import bundles
print(bundles.keys())

start_session = pd.Timestamp('2012-1-3', tz='utc')
end_session = pd.Timestamp('2012-1-11', tz='utc')

register(
'custom2-jupyter',
csvdir_equities(
["daily"],
'/Users/x/'),
calendar_name='NYSE', # US equities
start_session = start_session,
end_session = end_session
)

!zipline ingest -b custom2-jupyter
ERROR

............ So if I run these codes in jupyterlab, I get an error bundle not registered. However, if I copy following blocks into a extension.py file (which is saved in the folder C:\\Users\\x\\.zipline ) & run it in jupyterlab it magically works:

import pandas as pd

from zipline.data.bundles import register
from zipline.data.bundles.csvdir import csvdir_equities

start_session = pd.Timestamp('2012-1-3', tz='utc')
end_session = pd.Timestamp('2012-1-11', tz='utc')

register(
    'custom2-jupyter',
    csvdir_equities(
        ['daily'],
        'C:/Users/x/',
    ),
    calendar_name='NYSE', # US equities
    start_session=start_session,
    end_session=end_session
)

....... so I wrote the above codes in extension.py and run it in jupyter lab:

import os
os.getcwd()

os.chdir('C:\\Users\\x\\.zipline')
os.getcwd()

import numpy as np
import pandas as pd
from zipline.examples import buyapple
from zipline.api import order, record, symbol

%load_ext zipline
from zipline.data.bundles import register
from zipline.data.bundles.csvdir import csvdir_equities

from zipline.data.bundles import bundles
print(bundles.keys())

!python extension.py

!zipline ingest -b custom2-jupyter

.... then I get these warnings, but it ingests the data:

Merging daily equity files:
[2023-01-30 20:49:28.394021] INFO: zipline.data.bundles.core: Ingesting custom2-jupyter.
C:\Users\x\miniconda3\envs\clone_zipline\lib\site-packages\zipline\data\bundles\csvdir.py:226: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  divs_splits["splits"] = splits.append(split)
C:\Users\x\miniconda3\envs\clone_zipline\lib\site-packages\zipline\data\bundles\csvdir.py:241: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  divs_splits["divs"] = divs.append(div)
C:\Users\x\miniconda3\envs\clone_zipline\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
C:\Users\x\miniconda3\envs\clone_zipline\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
C:\Users\x\miniconda3\envs\clone_zipline\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
C:\Users\x\miniconda3\envs\clone_zipline\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
C:\Users\x\miniconda3\envs\clone_zipline\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
C:\Users\x\miniconda3\envs\clone_zipline\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
C:\Users\x\miniconda3\envs\clone_zipline\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

Loading custom pricing data: 
 | META: sid 0


..... then I run a simple test to see if it has any data:

```
from zipline import run_algorithm

def initialize(context):
    pass

def handle_data(context, data):
    order(symbol('META'),10)
    record(META=data.current(symbol('META'), 'price'))

start, end = (pd.Timestamp("2012-1-1", tz="UTC"), pd.Timestamp("2012-1-11", tz="UTC"))
capital_base = 1e7
performance = run_algorithm(start=start,
                            end=end,
                            initialize=initialize,
                            capital_base=capital_base,
                            handle_data=handle_data,
                            bundle='custom2-jupyter'
                            )

performance

```

..... the data that it shows is a little bit strange, but I was not able to generate even this before:


![Capture](https://user-images.githubusercontent.com/121390791/215596159-65b0e3dd-f7b2-4878-a64b-3aa92347802a.JPG)

**Comment by jasonstrimpel** [comment]
When calling the Zipline command line, extensions are loaded from the extensions.py file. When you write the extension code in Jupyter, Zipline does not see it and cannot register your bundle in memory. In other words, don't write your extension code in Jupyter Notebook, write them in the extensions file like in the documentation I shared.

The pandas warnings are because some features used in Zipline are being removed. Make sure you use the version of pandas that is in Zipline requirements.txt file.

I don't know what the other warnings are about.

**Comment by thetehtrader** [comment]
thank you

**Comment by stefan-jansen** [comment]
Closing in the hope this was resolved; feel free to reopen if the issue persists.
