### ISSUE TITLE
Zipline Reloaded v.2.0.0.post1 requires yfinance with broken dependency

### ISSUE THREAD

**Issue by RichardDale** [stefan-jansen/zipline-reloaded#17]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>
Win10/64
Python 3.8
Anaconda
</details>

# Reproduction Steps

mamba install -c ml4t -c conda-forge zipline-reloaded=2.0.0.post1

can also be demonstrated with:

mamba install -c ml4t -c conda-forge yfinance

# Workaround

The multitasking pacakge IS available on the ranaroussi channel, so this is a workaround (or solution I guess):

mamba install -c ml4t -c conda-forge -c ranaroussi zipline-reloaded=2.0.0.post1

Cheers,
Richard.

**Comment by stefan-jansen** [comment]
Sorry, just now updated the instructions to read:

```bash
conda install -c ml4t -c conda-forge -c ranaroussi zipline-reloaded
```
