### ISSUE TITLE
Doesn't work with Pandas 2.0 and SQLAlchemy 2.0

### ISSUE THREAD

**Issue by dsdante** [stefan-jansen/zipline-reloaded#184]
Zipline doesn't work with Pandas 2.0 ([`"Algorithm should have a utc datetime"`](https://pastebin.com/raw/8gm4EKnP)) and SQLAlchemy 2.0 ([`"The 'future' parameter passed to create_engine() may only be set to True"`](https://pastebin.com/raw/tzrzmGak)).

The latest pre-2.0 versions seem to work, at least I can run a simple test program:
```python
import pandas as pd
import pandas_datareader.data as web
from zipline import run_algorithm
from zipline.api import order, record, symbol


def initialize(context):
    pass


def handle_data(context, data):
    order(symbol('AAPL'), 10)
    record(AAPL=data.current(symbol('AAPL'), 'price'))


start = pd.Timestamp('2014')
end = pd.Timestamp('2018')

sp500 = web.DataReader('SP500', 'fred', start, end).SP500
benchmark_returns = sp500.pct_change()

result = run_algorithm(start=start,
                       end=end,
                       initialize=initialize,
                       handle_data=handle_data,
                       capital_base=100000,
                       benchmark_returns=benchmark_returns,
                       bundle='quandl',
                       data_frequency='daily')
```

Environment:
* Kubuntu 22.04
* Python 3.10
* pip
* zipline-reloaded 2.4

**Comment by BirdyLiu6471023** [comment]
Hi, did you solve this ["The 'future' parameter passed to create_engine() may only be set to True"] ? I have the same mistake here.

**Comment by MBounouar** [comment]
pandas = 2 ans sqlalchemy >= 2 , introduce non-backward compatible changes. You need to downgrade pandas and sqlalchemy

**Comment by stefan-jansen** [comment]
Please retry with latest, just released version.
