### ISSUE TITLE
how to install 2.4 version using conda?

### ISSUE THREAD

**Issue by quant2008** [stefan-jansen/zipline-reloaded#187]
I use "conda install -c ml4t -c conda-forge -c ranaroussi zipline-reloaded" to insall zipline-reload on windows, the version it installed is 2.2.0. This version has Turkey key error . I wonder how to install 2.4 version using conda?

**Comment by RiseT** [comment]
Simply use `conda install -c conda-forge zipline-reloaded` instead.

Since the packages have been migrated to conda-forge, the `ml4t` channel is not updated anymore.

**Comment by RichardDale** [comment]
The Installation section here needs a bit of a refresh:
https://zipline.ml4trading.io/

**Comment by stefan-jansen** [comment]
Docs updated, finally, sorry for the delay.
