### ISSUE TITLE
Zipline Reloaded 2.4 run issue: DateOutOfBounds

### ISSUE THREAD

**Issue by ntsvetkov80** [stefan-jansen/zipline-reloaded#190]
Dear Zipline Maintainers,

I just installed Zipline 2.4 on my machine (Win10 with Anaconda 2023.03-1 environment running Python 3.10). I'm using Norgate data as data provider.
 
I cannot run any algorithms that worked prior to the 2.4 release, nor can I ingest bundles.

## Reproduction Steps

1. Create conda environment and install Zipline Reloaded 2.4 using the following commands:

conda create -y -n zip310 python=3.10
conda activate zip310
conda install -y -c conda-forge mamba
mamba install -y -c conda-forge zipline-reloaded pyfolio-reloaded
mamba install -y -c conda-forge jupyter logbook
pip install norgatedata zipline-norgatedata
if not exist %HOMEPATH%\.zipline mkdir %HOMEPATH%\.zipline
if not exist %HOMEPATH%\.zipline\extension.py copy /b NUL %HOMEPATH%\.zipline\extension.py

2. Ensure your Norgate data updater is installed with an active futures subscription
4. Register any futures bundle in the .zipline\extension.py file
5. Try to ingest the bundle
6. Additionally, try running a Zipline futures algorithm on any already ingested bundle prior to installing Zip 2.4.

## Expected results

The bundle should have been ingested, and algorithm should have run as usual.

## Actual result

Instead of ingesting the bundle, Zipline returns the following

> C:\<installation directory>\envs\zip310\lib\site-packages\zipline\__main__.py:60: UserWarning: Failed to load extension: 'C:\\(homepath)\\.zipline\\extension.py'
> Parameter `date` receieved as '1998-01-01 00:00:00' although cannot be earlier than the first session of calendar 'XNYS' ('1998-01-02 00:00:00').
>   load_extensions(
> Error: No bundle registered with the name 'my_futures_bundle'

When trying to run a ZIpline Reloaded 2.4 algo on a previously ingested bundle, it spits out the following error message:

> DateOutOfBounds: Parameter `date` receieved as '1998-01-01 00:00:00' although cannot be earlier than the first session of calendar 'XNYS' ('1998-01-02 00:00:00').

Please let me know if there is any additional information I can provide to help resolve this issue. Thank you.

Sincerely,
Nikolay

**Comment by MBounouar** [comment]
Unfortunately, because of the changes introduced by **exchange-calendars** since version 4,  **sessions are now timezone-naive**.
You need to re-ingest data bearing in mind that you might need to re-align your data

**Comment by ntsvetkov80** [comment]
Thanks, problem solved.

What really stumped me was that I was trying to ingest a futures bundle, and Zipline said the error was in the XNYSE exchange calendar, not in the futures calendar. I had around 20 different registered bundles in my extensions.py file and it didn't occur to me I had to edit ALL of their start dates to make them compatible with their respective calendars, before I could ingest my futures bundle.

Maybe that could be fixed in future releases, to make zipline just look to the next available trading date in the calendar.
