### ISSUE TITLE
assets-7.sqlite' doesn't exist

### ISSUE THREAD

**Issue by azsaha123** [stefan-jansen/zipline-reloaded#211]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: Windows 11
* Python Version: 3.10.9
* Python Bitness: 64
* How did you install Zipline: pip
* Python packages: pip install zipline-reloaded

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

On running the 04_single_factor_zipline.ipynb script, getting the error "assets-7.sqlite' doesn't exist" when executing the line %%zipline --start 2015-1-1 --end 2018-1-1 --output single_factor.pickle --no-benchmark --bundle quandl 

## What steps have you taken to resolve this already?

Tried running zipline ingest -b quandl
as described in 
https://stefan-jansen.github.io/machine-learning-for-trading/installation/

![Screenshot 2023-07-20 205059](https://github.com/stefan-jansen/zipline-reloaded/assets/90947985/b1d30782-ef8e-4d24-8746-20b06fea1854)

**Comment by MBounouar** [comment]
try to re-install latest zipline version there was a recent fix

**Comment by RichardDale** [comment]
Note that the conda-forge hasn't yet been updated with these fixes:
https://anaconda.org/conda-forge/zipline-reloaded/files

Does conda-forge need a bit of gentle persuasion to run?

**Comment by azsaha123** [comment]
Thanks so much, Richard! Should I try reinstalling zipline-reloaded in a couple of days?

**Comment by stefan-jansen** [comment]
conda-forge has been updated last week so closing this. feel free to reopen if issues persist.
