### ISSUE TITLE
No conda package for zipline-reloaded compatible with Python 3.11

### ISSUE THREAD

**Issue by phelps-sg** [stefan-jansen/zipline-reloaded#214]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: (Windows Version or `$ uname --all`)

~~~
Linux pop-os 6.4.6-76060406-generic #202307241739~1690928105~22.04~d567a38 SMP PREEMPT_DYNAMIC Tue A x86_64 x86_64 x86_64 GNU/Linux
~~~

* Python Version: `$ python --version`

~~~
Python 3.11.4
~~~

* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`

~~~
64
~~~

* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)  conda
* Python packages: `$ pip freeze` or `$ conda list`

~~~
# packages in environment at /home/sphelps/mambaforge/envs/zipline-tardis-bundle/envs/zipline-3.11:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.43.0               h2797004_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
openssl                   3.1.2                hd590300_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
python                    3.11.4          hab00c5b_0_cpython    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                68.1.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
~~~
</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

There is no conda package for zipline-reloaded compatible with Python 3.11

* What did you expect to happen?

`mamba install -c conda-forge zipline-reloaded` should result in successful installation with Python 3.11, or alternatively with the following `environment.yml`:

~~~yaml
name: zipline-3.11
channels:
 - conda-forge
dependencies:
 - python=3.11
 - zipline-reloaded
~~~

* What happened instead?

Installation fails with:

~~~
Could not solve for environment specs
The following packages are incompatible
└─ zipline-reloaded   is installable with the potential options
   ├─ zipline-reloaded [2.4|3.0|3.0.3] would require
   │  └─ python >=3.10,<3.11.0a0 , which can be installed;
   ├─ zipline-reloaded [2.4|3.0|3.0.3] would require
   │  └─ python >=3.8,<3.9.0a0 , which can be installed;
   └─ zipline-reloaded [2.4|3.0|3.0.3] would require
      └─ python >=3.9,<3.10.0a0 , which can be installed.
~~~

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.  Configure a conda environment with Python 3.11 (see above)
2.  Install zipline-reloaded using conda or mamba
...

## What steps have you taken to resolve this already?

Browsing the files on conda-forge shows that only packages available are for Python < 3.11 which is inconsistent with the Python badges listed in the README.md

# Anything else?

...

Sincerely,
Steve Phelps

**Comment by alb7** [comment]
Same here, hopefully this is just about updating the package requirements?

**Comment by 0xrushi** [comment]
Conda package has been deprecated, zipline-reloaded no more available as a conda package

**Comment by stefan-jansen** [comment]
Conda packages are available via [conda-forge](https://anaconda.org/conda-forge/zipline-reloaded and update as dependencies become available.
