### ISSUE TITLE
help please 🙏 error running conda install -c ml4t zipline-reloaded

### ISSUE THREAD

**Issue by heapallocation** [stefan-jansen/zipline-reloaded#231]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: (Windows Version or `$ uname --all`) macOS Ventura 3.11
* Python Version: `$ python --version` Python 3.11.6
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'` 64
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`) conda install -c ml4t zipline-reloaded
* Python packages: `$ pip freeze` or `$ conda list`

# Name                    Version                   Build  Channel
bzip2                     1.0.8                h10d778d_5    conda-forge
ca-certificates           2023.7.22            h8857fd0_0    conda-forge
libexpat                  2.5.0                hf0c8a7f_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libsqlite                 3.44.0               h92b6c6a_0    conda-forge
libzlib                   1.2.13               h8a1eda9_5    conda-forge
ncurses                   6.4                  h93d8f39_2    conda-forge
openssl                   3.1.4                hd75f5a5_0    conda-forge
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
python                    3.11.6          h30d4d87_0_cpython    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h1abcd95_1    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
wheel                     0.41.3             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

Getting this error on running the install command conda install -c ml4t zipline-reloaded:

Could not solve for environment specs
The following packages are incompatible
├─ pin-1 is installable with the potential options
│  ├─ pin-1 1 would require
│  │  └─ python 3.11.* , which can be installed;
│  └─ pin-1 1 would require
│     └─ python 3.11.* , which can be installed;
└─ zipline-reloaded is not installable because there are no viable options
   ├─ zipline-reloaded [2.0.0.post1|2.0.0rc4|2.1.1|2.2.0|2.3] would require
   │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
   ├─ zipline-reloaded [2.0.0.post1|2.0.0rc4|2.1.1|2.2.0|2.3] would require
   │  └─ python >=3.7,<3.8.0a0 , which conflicts with any installable versions previously reported;
   └─ zipline-reloaded [2.4|3.0|3.0.3] conflicts with any installable versions previously reported.

Which is weird as python is installed. I have activated environment too. Any help would be greatly appreciated!

Sincerely,
A hopeful Zipliner🤞

**Comment by heapallocation** [comment]
Managed to workaround it with:
`conda create -n env_zipline python=3.10`
`conda install -c conda-forge zipline-reloaded=3.0.3=py310hc1335a1_0`

**Comment by RiseT** [comment]
Try this, which should be the standard way of installing zipline-reloaded:
```
conda create -n env_zipline
conda activate env_zipline
conda install -c conda-forge zipline-reloaded
```

Python 3.11 currently only seems to work with a pip install (without conda) of zipline (never tried it, though). See https://github.com/stefan-jansen/zipline-reloaded/issues/214

**Comment by heapallocation** [comment]
thanks @RiseT ! Will give this a shot with the next time.
