### ISSUE TITLE
TA-LIB wget downloads old version ?

### ISSUE THREAD

**Issue by NorthDecoder** [stefan-jansen/zipline-reloaded#234]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: (Windows Version or `$ uname --all`)
  * `Linux my-server-name 6.5.8-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 20 15:53:48 UTC 2023 x86_64 GNU/Linux`
* Python Version: `$ python --version`
  * `Python 3.11.6` 
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
  * `64 `
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
  * Not installed yet, working on the prerequisites
* Python packages: `$ pip freeze` or `$ conda list`

     ```bash
     argcomplete==2.0.0
     attrs==22.2.0
     cffi==1.15.1
     charset-normalizer==3.1.0
     cloud-init==23.1.2
     cockpit @ file:///builddir/build/BUILD/cockpit-304/tmp/wheel/cockpit-304-py3-none-any.whl
     coloredlogs==15.0.1
     configobj==5.0.8
     cryptography==37.0.2
     dasbus==1.7
     dbus-python==1.3.2
     deprecation==2.1.0
     distro==1.8.0
     dnf==4.18.1
     fail2ban==1.0.2
     file-magic==0.4.0
     gpg==1.17.1
     humanfriendly==10.0
     idna==3.4
     img2pdf==0.4.4
     iotop==0.6
     Jinja2==3.0.3
     jsonpatch==1.21
     jsonpointer==2.0
     jsonschema==4.17.3
     libcomps==0.1.20
     libdnf==0.72.0
     lxml==4.9.2
     markdown-it-py==2.2.0
     MarkupSafe==2.1.2
     mdurl==0.1.2
     netifaces==0.11.0
     nftables==0.1
     oauthlib==3.2.2
     ocrmypdf==14.4.0
     olefile==0.46
     packaging==23.0
     pdfminer.six==20221105
     pexpect==4.8.0
     pikepdf==8.4.1
     Pillow==9.5.0
     pluggy==1.0.0
     ply==3.11
     prettytable==0.7.2
     psutil==5.9.5
     ptyprocess==0.7.0
     pycparser==2.20
     Pygments==2.14.0
     PyGObject==3.44.1
     PyJWT==2.6.0
     pyparsing==3.0.9
     pyrsistent==0.19.3
     pyserial==3.5
     PySocks==1.7.1
     python-augeas==1.1.0
     python-dateutil==2.8.2
     PyYAML==6.0
     reportlab==4.0.4
     requests==2.28.2
     rich==13.3.5
     rpm==4.18.2
     selinux==3.5
     sepolicy==3.5
     setools==4.4.3
     setroubleshoot==3.3.32
     six==1.16.0
     sos==4.5.1
     systemd-python==235
     tqdm==4.66.1
     urllib3==1.26.18
     ```  

</details>

Now that you know a little about me, let me tell you about the issue I am having:

# Description of Issue

Installation instructions at
[docs/source/install.rst line 92](https://github.com/stefan-jansen/zipline-reloaded/blob/4a648f6a0e7bf61d9bfe46f7152166cf1f13c5d8/docs/source/install.rst?plain=1#L92)  suggests
`$ wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz`

* What did you expect to happen?
  * I expected to receive the latest available version 
* What happened instead?
  * The file received was dated September 14, 2007

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Run the wget command to download the file

## What steps have you taken to resolve this already?
1. Researching the website [ta-lib.org](https://ta-lib.org/), I see a link to a repository that claims to be the latest version with a release candidate dated August 21, 2016 [:link:](https://github.com/TA-Lib/ta-lib/tags)
2. It seems unwise to attempt an install on a version that is sixteen years old, so I have not tried yet.

# Anything else?
Maybe a footnote would be good here explaining the different versions.

Sincerely,
`$ whoami`

**Comment by stefan-jansen** [comment]
This question would be better posted in the TA-Lib repo.
