### ISSUE TITLE
execute order at next bar‘s open price

### ISSUE THREAD

**Issue by quant2008** [stefan-jansen/zipline-reloaded#235]
Hello, [this post ](https://github.com/quantopian/zipline/pull/1512) shows how to Add slippage models to execute order at next bar's open price. I wonder if this solution is correct and if it is implemented in zipline-reloaded?

**Comment by gnzsnz** [comment]
i'm interested in the possibility of having orders at open price

**Comment by stefan-jansen** [comment]
Appears to be duplicate of #132; PRs are always welcome.
