### ISSUE TITLE
zipline-reloaded installation failing through conda/pip/local on macOS m1pro (sonoma 14.2.1)

### ISSUE THREAD

**Issue by Rishang007** [stefan-jansen/zipline-reloaded#237]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: macOS M1-Pro Sonoma 14.2.1
* Python Version: Python 3.9.18
* Python Bitness: 64
* How did you install Zipline: tried all options including locally downloading .tar file and using conda and pip. Same issue
* Python packages: 
 Name                    Version                   Build  Channel
blas                      1.0                    openblas  
bottleneck                1.3.5            py39heec5a64_0  
ca-certificates           2023.12.12           hca03da5_0  
certifi                   2024.2.2         py39hca03da5_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
idna                      3.4              py39hca03da5_0  
inflection                0.5.1            py39hca03da5_0  
libcxx                    14.0.6               h848a8c0_0  
libffi                    3.4.4                hca03da5_0  
libgfortran               5.0.0           11_3_0_hca03da5_28  
libgfortran5              11.3.0              h009349e_28  
libopenblas               0.3.21               h269037a_0  
llvm-openmp               14.0.6               hc6e5704_0  
more-itertools            10.1.0           py39hca03da5_0  
ncurses                   6.4                  h313beb8_0  
numexpr                   2.8.7            py39hecc3335_0  
numpy                     1.26.3           py39h3b2db8e_0  
numpy-base                1.26.3           py39ha9811e2_0  
openssl                   3.0.13               h1a28f6b_0  
pandas                    2.1.4            py39h46d7db6_0  
pip                       23.3.1           py39hca03da5_0  
python                    3.9.18               hb885b13_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-tzdata             2023.3             pyhd3eb1b0_0  
pytz                      2023.3.post1     py39hca03da5_0  
quandl                    3.6.1            py39hca03da5_0  
readline                  8.2                  h1a28f6b_0  
requests                  2.31.0           py39hca03da5_1  
setuptools                68.2.2           py39hca03da5_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.41.2               h80987f9_0  
tk                        8.6.12               hb8d0fd4_0  
tzdata                    2023d                h04d1e81_0  
urllib3                   2.1.0            py39hca03da5_0  
wheel                     0.41.2           py39hca03da5_0  
xz                        5.4.5                h80987f9_0  
zlib                      1.2.13               h5a0b063_0 

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
I expected it to install zipline-reloaded when I use the command "conda install -c conda-forge zipline-reloaded" **OR** "pip install zipline-reloaded"
* What happened instead?
**Using Conda**
"PackagesNotFoundError: The following packages are not available from current channels:

  - zipline-reloaded

Current channels:

  - https://conda.anaconda.org/conda-forge
  - defaults
 "

**Using pip**
#include "H5public.h"
               ^~~~~~~~~~~~
      1 error generated.
      cpuinfo failed, assuming no CPU features: 'flags'
      * Using Python 3.9.18 (main, Sep 11 2023, 08:25:10)
      * Found cython 3.0.8
      * USE_PKGCONFIG: True
      * Found conda env: ``/Users/rishangprashnani/anaconda3/envs/comp_in``
      .. ERROR:: Could not find a local HDF5 installation.
         You may need to explicitly state where your local HDF5 headers and
         library can be found by setting the ``HDF5_DIR`` environment
         variable or by using the ``--hdf5`` command-line option.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. On macOS install using conda
2. On macOS install using pip
3. Locally download the .tar file and install using pip or .whl file 
...

## What steps have you taken to resolve this already?
Tried it using local download of the package.
Changed python versions
tried using different commands like - "$conda install ml4t::zipline-reloaded" and "$conda install conda-forge::zipline-reloaded"

Sincerely,
Rishang

**Comment by 0xrushi** [comment]
This works 

```
conda install -c conda-forge ta-lib hdf5 pytables
pip install zipline-reloaded
```

**Comment by stefan-jansen** [comment]
There should be a new [conda package](https://anaconda.org/conda-forge/zipline-reloaded) soon.
