### ISSUE TITLE
TypeError: Expected data of type float64 for column 'ratio', but got 'object'.

### ISSUE THREAD

**Issue by mac133k** [stefan-jansen/zipline-reloaded#31]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: Linux localhost.localdomain 5.11.17-300.fc34.x86_64 #1 SMP Wed Apr 28 14:21:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 3.9.4
* Python Bitness: 64
* How did you install Zipline: pip
* Python packages: Too long, didn't paste in

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
I was trying to create a bundle out of CSV files containing LSE stock prices, so I set the calendar to LSE. Prior to the ingestion I imputed the missing dates into all CSVs like they said in this old Quantopian thread: https://quantopian-archive.netlify.app/forum/threads/data-bundle-error-help.html and as a result I encountered the same error the last person in that thread reported. Unfortunately there was no follow-up on that thread and no workaround provided. It seems like zipline-reloaded inherited the same behavior. I wonder how to fix it.

* What did you expect to happen?
A new bundle to be created.
* What happened instead?
Zipline threw the error:
`TypeError: Expected data of type float64 for column 'ratio', but got 'object'.`

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Download prices to CSVs.
2. Expand the dates to include the missing dates according to LSE calendar.
3. Attempt to ingest the bundle.
...

## What steps have you taken to resolve this already?
Searching for answers online.

...

Sincerely,
mac133k

**Comment by mac133k** [comment]
Actually I've just got the same error trying to create a bundle from CSVs with US stock prices using NYSE calendar, so it must be something else.

**Comment by MBounouar** [comment]
Could you please check which version of pandas you are using? if it's 1.3, try to downgrade to 1.2.5

If that's not the case it's a bit hard to guess what could be happening.

Otherwise,  maybe you could try the examples from [https://github.com/hsm207/trading_evolved](https://github.com/hsm207/trading_evolved/blob/master/notebooks/15_Futures_Trend_Following/01_futures_bundle.ipynb)
Last time (2months ago) I tried these CSV ingestion examples they worked without issues.

**Comment by mac133k** [comment]
I had pandas==1.2.4, then I upgraded to 1.2.5 and the issue still persists. What I had been doing was very similar to these examples. When I try to ingest my CSV collection into a bundle zipline loads all the files and fails at the last step:
'''
Merging daily equity files:  [####################################]     
Traceback (most recent call last):
  File "/usr/local/bin/zipline", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib64/python3.9/site-packages/zipline/__main__.py", line 389, in ingest
    bundles_module.ingest(
  File "/usr/local/lib64/python3.9/site-packages/zipline/data/bundles/core.py", line 443, in ingest
    bundle.ingest(
  File "/usr/local/lib64/python3.9/site-packages/zipline/data/bundles/csvdir.py", line 84, in ingest
    csvdir_bundle(
  File "/usr/local/lib64/python3.9/site-packages/zipline/data/bundles/csvdir.py", line 185, in csvdir_bundle
    adjustment_writer.write(
  File "/usr/local/lib64/python3.9/site-packages/zipline/data/adjustments.py", line 687, in write
    self.write_frame("splits", splits)
  File "/usr/local/lib64/python3.9/site-packages/zipline/data/adjustments.py", line 443, in write_frame
    return self._write(
  File "/usr/local/lib64/python3.9/site-packages/zipline/data/adjustments.py", line 409, in _write
    raise TypeError(
TypeError: Expected data of type float64 for column 'ratio', but got 'object'.
'''

**Comment by MBounouar** [comment]
As the error message suggests the type is object and expected is float. 
Usually that happens when one more of your data points cannot be inferred as floats and pandas will simply assume objects type.
Maybe you are including data  that you shouldn't when processing the csv files.

**Comment by mac133k** [comment]
I have found the bug: one of my scripts that cleans up the data and prepares for ingestion was adding the split and dividend columns before performing the index expansion according to the trading calendar which adds rows with NaN values into dataframes where the days were missing. NaN values are not an issue for prices and volume, but apparently are for splits resulting with the error above (it complained about the 'ratio').

**The fix:**
When preparing data for ingestion insert the split column after the date index expansion, so that it does not contain NaN values.

Thus the problem was not related to the code, but to the data being ingested.
