### ISSUE TITLE
Switch to exchange_calendars forked from trading_calendars?

### ISSUE THREAD

**Issue by maartenb** [stefan-jansen/zipline-reloaded#38]
Maybe switch to [exchange_calendars](https://github.com/gerrymanoim/exchange_calendars)

See e.g. [Pandas fix](https://github.com/gerrymanoim/exchange_calendars/pull/41)

**Comment by stefan-jansen** [comment]
That's indeed the plan, just need to do some work to prevent unintended consequences.

**Comment by stefan-jansen** [comment]
Addressed by #57.
