### ISSUE TITLE
Decoupled bcolz, using parquet/pyarrow.dataset/tstables(hdf5)/rocksdb/...

### ISSUE THREAD

**Issue by zfsamzfsam** [stefan-jansen/zipline-reloaded#6]
parquet/pyarrow.dataset
		https://arrow.apache.org/docs/python/dataset.html
		https://arrow.apache.org/docs/python/parquet.html

	tstables(hdf5)
		https://github.com/afiedler/tstables

	rocksdb
		https://github.com/JaysonAlbert/zipline/blob/master/zipline/data/rocksdb_bars.py
		class RocksdbMinuteBarWriter
		class RocksdbMinuteBarReader

**Comment by stefan-jansen** [comment]
Agreed, need a more flexible / updated backend. Have looked at the first two and a few others; will review the last one on your list. `tstables` is a bit old and current HDF5 pandas implementation might be a workable solution. There's also TimeScaleDB and related.

**Comment by apologeticallypervy** [comment]
@stefan-jansen I can take a look at this. Are pull requests welcome?

**Comment by stefan-jansen** [comment]
@HumanRupert sorry for the late reply, somehow missed your comment and was ooo for a little while. Yes, PR are more than welcome.

**Comment by stefan-jansen** [comment]
Closing for now due to lack of activity. PRs remain welcome.
