### ISSUE TITLE
Links to the examples directory are wrong

### ISSUE THREAD

**Issue by chronoverse** [stefan-jansen/zipline-reloaded#67]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

I am reporting a problem with documentation so the development environment does not really matter.

* Operating System: Darwin mbp13.lan 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
* Python Version: Python 3.8.12
* Python Bitness: 64
* How did you install Zipline: pip
* Python packages: `$ pip freeze`
<pre>
(venv) chronoverse:zipline-reloaded>pip freeze
alembic==1.7.4
bcolz-zipline==1.2.4
Bottleneck==1.3.2
certifi==2021.10.8
charset-normalizer==2.0.7
click==8.0.3
empyrical-reloaded==0.5.8
greenlet==1.1.2
h5py==3.5.0
idna==3.3
importlib-metadata==4.8.1
importlib-resources==5.4.0
intervaltree==3.1.0
iso3166==2.0.2
iso4217==1.6.20180829
Logbook==1.5.3
lru-dict==1.1.7
lxml==4.6.3
Mako==1.1.5
MarkupSafe==2.0.1
multipledispatch==0.6.0
multitasking==0.0.9
networkx==2.6.3
numexpr==2.7.3
numpy==1.21.3
pandas==1.2.5
pandas-datareader==0.10.0
patsy==0.5.2
python-dateutil==2.8.2
python-interface==1.6.1
pytz==2021.3
requests==2.26.0
scipy==1.7.1
six==1.16.0
sortedcontainers==2.4.0
SQLAlchemy==1.4.26
statsmodels==0.13.0
TA-Lib==0.4.21
tables==3.6.1
toolz==0.11.1
trading-calendars==2.1.1
urllib3==1.26.7
yfinance==0.1.64
zipline-reloaded==2.1.1
zipp==3.6.0

</pre>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
There three places the link to `zipline/examples` should be <https://github.com/stefan-jansen/zipline-reloaded/tree/main/src/zipline/examples>

* What happened instead?
The link is <https://github.com/stefan-jansen/zipline-reloaded/tree/main/zipline/examples>. So when click on the
link in the doc, I got a 404.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

See the link at the bottom of README.md at <https://github.com/stefan-jansen/zipline-reloaded>

## What steps have you taken to resolve this already?
I can submit a pull request, if I can be made to r/w to the repo

Sincerely,
chronoverse

**Comment by MBounouar** [comment]
If you want to make a PR you have to create first a fork
[creating-pull-request-from-a-fork](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by stefan-jansen** [comment]
Should be fixed on `main` - I only saw one wrong link, feel free to reopen or PR if I missed anything.
