### ISSUE TITLE
Unable to install zipline-reloaded using Conda on Win 10/64

### ISSUE THREAD

**Issue by RichardDale** [stefan-jansen/zipline-reloaded#7]
Dear Zipline Maintainers,

# Environment

<details>

* Operating System: Win10/64bit
* Python Version: 3.8.8
* Python Bitness: 64
* How did you install Zipline: conda
* Python packages: 
ca-certificates           2021.4.13            haa95532_1
certifi                   2020.12.5        py38haa95532_0
openssl                   1.1.1k               h2bbff1b_0
pip                       21.0.1           py38haa95532_0
python                    3.8.8                hdbf39b2_5
setuptools                52.0.0           py38haa95532_0
sqlite                    3.35.4               h2bbff1b_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2                      py38_0

conda --version reports:
Conda v4.9.2

</details>

# Description of Issue

* Whilst attempting to install zipline-reloaded, with the recomended conda environment and install instructions a nebulous error message occurs:

```failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available version
```

Full error message here:

```
(env_zipline) C:\Users\richa>conda install -v -c ml4t zipline-reloaded
Collecting package metadata (current_repodata.json): ...working... Unable to retrieve repodata (response: 404) for https://conda.anaconda.org/ml4t/win-64/current_repodata.json

done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working...
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
Traceback (most recent call last):
  File "C:\Users\richa\anaconda3\lib\site-packages\conda\cli\install.py", line 261, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "C:\Users\richa\anaconda3\lib\site-packages\conda\core\solve.py", line 114, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "C:\Users\richa\anaconda3\lib\site-packages\conda\core\solve.py", line 157, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "C:\Users\richa\anaconda3\lib\site-packages\conda\core\solve.py", line 281, in solve_final_state
    ssc = self._run_sat(ssc)
  File "C:\Users\richa\anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "C:\Users\richa\anaconda3\lib\site-packages\conda\core\solve.py", line 815, in _run_sat
    ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs),
  File "C:\Users\richa\anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "C:\Users\richa\anaconda3\lib\site-packages\conda\resolve.py", line 1320, in solve
    raise UnsatisfiableError({})
conda.exceptions.UnsatisfiableError:
Did not find conflicting dependencies. If you would like to know which
packages conflict ensure that you have enabled unsatisfiable hints.

conda config --set unsatisfiable_hints True


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\richa\anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "C:\Users\richa\anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "C:\Users\richa\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 83, in do_call
    return getattr(module, func_name)(args, parser)
  File "C:\Users\richa\anaconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "C:\Users\richa\anaconda3\lib\site-packages\conda\cli\install.py", line 308, in install
    raise e
  File "C:\Users\richa\anaconda3\lib\site-packages\conda\cli\install.py", line 295, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "C:\Users\richa\anaconda3\lib\site-packages\conda\core\solve.py", line 114, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "C:\Users\richa\anaconda3\lib\site-packages\conda\core\solve.py", line 157, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "C:\Users\richa\anaconda3\lib\site-packages\conda\core\solve.py", line 275, in solve_final_state
    ssc = self._add_specs(ssc)
  File "C:\Users\richa\anaconda3\lib\site-packages\conda\core\solve.py", line 704, in _add_specs
    ssc.r.find_conflicts(spec_set)
  File "C:\Users\richa\anaconda3\lib\site-packages\conda\resolve.py", line 352, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

## Reproduction Steps

1.  Start anaconda prompt in base environment
2. `conda create -n env_zipline python=3.8`
3. `conda activate env_zipline`
4.  `conda install -v -c ml4t zipline-reloaded`

## What steps have you taken to resolve this already?

I tried a brand new Conda installation (installed Miniconda3 from: 
https://docs.conda.io/en/latest/miniconda.html
on a clean VM - same issue.

Since this error message seems related:
Unable to retrieve repodata (response: 404) for https://conda.anaconda.org/ml4t/win-64/current_repodata.json
Thinking this might be a Conda bug, I tried:

```
conda activate base
conda update --all
conda activate env_zipline
conda install -v -c ml4t zipline-reloaded
```

This upgraded conda to v4.10.1, but bombed with same error

There was a hint to try using `conda config --set unsatisfiable_hints True`

So ran that then and again tried: `conda install -v -c ml4t zipline-reloaded`
but the same nebulous error resulted.

Also tried --force --nodeps, and --only-deps to try and figure out where the issue was coming from and --clobber.

Also tried it with a Python 3.9 environment instead:
```
conda activate base
conda create -n env_zipline39 python=3.9
conda activate env_zipline39
conda install -v -c ml4t zipline-reloaded
```

Same error in Python 3.9 environment too.

Then uninstalled Miniconda/Py39 downloaded Minicon3/Windows 64-bit/Python 3.8 from:
htts://conda.io/en/latest/miniconda.html

```
conda create -n env_zipline3 python=3.8
conda activate env_zipline38
conda install -v -c ml4t zipline-reloaded
```

This had the same issue.

Also tried a Python 3.7 environment - same issue.

Also tried 
```
conda activate base
conda update conda
```

then re-running the installs above - same issue.

Also tried with the full Anaconda installer (instead of Miniconda) - same issue.

I was going to try an earlier version of Zipline-reloaded, but only 2.0.0rc4 is available on Conda.

# Other

I have cloneable/pristine Win10/64 VMs that I can do further testing on this as required.  Happy to assist here.

Best regards,
Richard Dale

**Comment by RiseT** [comment]
For what it's worth, I've installed it successfully on Windows 10 (and additionally on Linux Mint), but I'm using [Miniforge ](https://github.com/conda-forge/miniforge)instead of Miniconda. The only difference that I know of is that is comes with conda-forge preconfigured as its default channel.

**Comment by stefan-jansen** [comment]
I have difficulties reproducing this but have heard the same from at least one other user. Similarly, on a fresh miniconda3-latest install on Windows 10 (64bit), 
```
conda update -n base conda -y
conda create -n zip-test python 3.8
conda activate zip-test
conda install zipline-reloaded -y
conda env export > zipline-reloaded.yml
``` 
produces the attached environment (change extension from .txt; GitHub does not support .yml).

`conda` certainly has its [share of issues](https://github.com/conda/conda/issues/9707) these days; it appears impossible to install zipline-reloaded and alphalens-reloaded together due to 'conflicts'. However, using [mamba](https://github.com/mamba-org/mamba) instead works both fine and fast. I'll update the instructions accordingly; see also [here](https://github.com/stefan-jansen/machine-learning-for-trading/tree/master/installation).

[zipline-reloaded.txt](https://github.com/stefan-jansen/zipline-reloaded/files/6381042/zipline-reloaded.txt)

**Comment by RichardDale** [comment]
Yes! Nice pickup there @RiseT.  @stefan-jansen thanks for the assistance today Stefan in resolving this one.

conda-forge fixed this nicely.

Here's the implications/instructions on using conda-forge:
https://conda-forge.org/docs/user/introduction.html

Here's the commands that worked nicely for me:
conda update -n base conda -y
conda config --add channels conda-forge
conda config --set channel_priority strict
conda install mamba -y
conda create -n env_zipline python=3.8
conda activate env_zipline
mamba install -c ml4t zipline-reloaded -y

If you prefer Python 3.9:

conda update -n base conda -y
conda config --add channels conda-forge
conda config --set channel_priority strict
conda install mamba -y
conda create -n zr39 python=3.9
conda activate zr39
mamba install -c ml4t zipline-reloaded -y

**Comment by RiseT** [comment]
Great this worked out. Dumb and somewhat off-topic question regarding Mamba: Can I mix usage of Conda and Mamba (e. g. update with Mamba a package installed with Conda and vice versa)?

**Comment by stefan-jansen** [comment]
The [README](https://github.com/mamba-org/mamba) says:
> At the same time, mamba utilize the same command line parser, package installation and deinstallation code and transaction verification routines as conda to stay as compatible as possible.

My understanding is that the key difference is that the solver works as expected (from apt etc) while using the same channel/package infrastructure. So mixing shouldn't create issues - assuming you want to start using mamba with an env created with conda. Note that mamba works with the same env files.

My experience so far - and I haven't used mamba for long but lost way too much time with conda - mamba just works while conda simply doesn't for anything but trivial installs.

**Comment by RiseT** [comment]
@stefan-jansen Fyi, the old installation instructions (without `-c conda-forge` are still [here](https://anaconda.org/ml4t/zipline-reloaded). Ignore this comment if this will get updated automatically with the next release. No idea how this works.

**Comment by Rishang007** [comment]
Hi, 
The zipline-reloaded installation is not working using conda-forge as it shows package not found.

Error-

PackagesNotFoundError: The following packages are not available from current channels:

  - zipline-reloaded
