### ISSUE TITLE
backtesting with custom bundle 

### ISSUE THREAD

**Issue by ramkikannan** [stefan-jansen/zipline-reloaded#72]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: OSX Mojave
* Python Version: `Python 3.8.6`
* Python Bitness: `64`
* How did you install Zipline: (`pip` )
* Python packages: `$ pip freeze` 
alembic==1.7.4
anyio==3.3.4
appnope==0.1.2
argon2-cffi==21.1.0
async-generator==1.10
attrs==21.2.0
Authlib==0.15.5
autopep8==1.6.0
Babel==2.9.1
backcall==0.2.0
bcolz-zipline==1.2.4
bleach==4.1.0
Bottleneck==1.3.2
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.7
click==8.0.3
cryptography==35.0.0
cycler==0.10.0
Cython==0.29.24
debugpy==1.5.1
decorator==5.1.0
defusedxml==0.7.1
empyrical==0.5.5
empyrical-reloaded==0.5.8
entrypoints==0.3
greenlet==1.1.2
h11==0.12.0
h5py==3.5.0
httpcore==0.13.7
httpx==0.20.0
idna==3.3
importlib-metadata==4.8.1
importlib-resources==5.4.0
inflection==0.5.1
intervaltree==3.1.0
ipykernel==6.4.2
ipython==7.28.0
ipython-genutils==0.2.0
iso3166==2.0.2
iso4217==1.6.20180829
jedi==0.18.0
Jinja2==3.0.2
joblib==1.1.0
json5==0.9.6
jsonschema==4.1.2
jupyter-client==7.0.6
jupyter-core==4.8.1
jupyter-server==1.11.1
jupyterlab==3.2.1
jupyterlab-pygments==0.1.2
jupyterlab-server==2.8.2
kiwisolver==1.3.2
Logbook==1.5.3
lru-dict==1.1.7
lxml==4.6.3
Mako==1.1.5
MarkupSafe==2.0.1
matplotlib==3.4.3
matplotlib-inline==0.1.3
mistune==0.8.4
more-itertools==8.10.0
multipledispatch==0.6.0
multitasking==0.0.9
nbclassic==0.3.3
nbclient==0.5.4
nbconvert==6.2.0
nbformat==5.1.3
nest-asyncio==1.5.1
networkx==2.6.3
notebook==6.4.5
numexpr==2.7.3
numpy==1.21.3
outcome==1.1.0
packaging==21.0
pandas==1.2.5
pandas-datareader==0.10.0
pandas-ta==0.3.14b0
pandocfilters==1.5.0
parso==0.8.2
patsy==0.5.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.4.0
plotly==5.3.1
prometheus-client==0.11.0
prompt-toolkit==3.0.21
ptyprocess==0.7.0
pycodestyle==2.8.0
pycparser==2.20
pyfolio-reloaded==0.9.4
Pygments==2.10.0
pyOpenSSL==21.0.0
pyparsing==3.0.1
pyrsistent==0.18.0
python-dateutil==2.8.2
python-interface==1.6.1
pytz==2021.3
pyzmq==22.3.0
Quandl==3.6.1
requests==2.26.0
requests-unixsocket==0.2.0
rfc3986==1.5.0
scikit-learn==1.0.1
scipy==1.7.1
seaborn==0.11.2
Send2Trash==1.8.0
simplejson==3.17.5
six==1.16.0
sniffio==1.2.0
sortedcontainers==2.4.0
SQLAlchemy==1.4.26
statsmodels==0.13.0
TA-Lib==0.4.21
tables==3.6.1
tenacity==8.0.1
terminado==0.12.1
testpath==0.5.0
threadpoolctl==3.0.0
toml==0.10.2
toolz==0.11.1
tornado==6.1
trading-calendars==2.1.1
traitlets==5.1.1
trio==0.19.0
trio-websocket==0.9.2
unsync==1.4.0
urllib3==1.26.7
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.2.1
websockets==10.0
wrapt==1.13.3
wsproto==1.0.0
yfinance==0.1.64
zipline-reloaded==2.1.1
zipp==3.6.0

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I tested the asset allocation with the custom bundle from the zipline_bundle project with the https://github.com/aspromatis/Backtesting-RSI-Algo/backtest.py. I changed the code as below to include my own portfolio.

```
#%%
import talib
from zipline.api import order_target, record, symbol, order_target_percent

'''   
This example algorithm uses the Relative Strength Index indicator as a buy/sell signal.
When the RSI is over 70, a stock can be seen as overbought and it's time to sell.
When the RSI is below 30, a stock can be seen as oversold and it's time to buy.
'''

# Setup our variables
def initialize(context):
    
    # what stock to trade - FAANG in this example
    # stocklist = ['FB', 'AMZN', 'AAPL', 'NFLX', 'GOOG']
    stocklist = ['SPY','TLT','IEF','GLD','DBC']
    context.securities = {
        'SPY': 0.25,
        'TLT': 0.3,
        'IEF': 0.3,
        'GLD': 0.075,
        'DBC': 0.075
    }

     # make a list of symbols for the list of tickers
    context.stocks = [symbol(s) for s in stocklist]
    
     # create equal weights of each stock to hold in our portfolio
     # context.target_pct_per_stock = 1.0 / len(context.stocks)
    
    # create initial RSI threshold values for low (oversold and buy signal) and high (overbought and sell signal)
    context.LOW_RSI = 30
    context.HIGH_RSI = 70

# Rebalance daily.
def handle_data(context, data):
    
    # Load historical pricing data for the stocks, using daily frequncy and a rolling 20 days
    prices = data.history(context.stocks, 'price', bar_count=20, frequency="1d")
    
    rsis = {}
    
    # Loop through our list of stocks
    for stock in context.stocks:
        # Get the rsi of this stock.
        rsi = talib.RSI(prices[stock], timeperiod=14)[-1]
        rsis[stock] = rsi
        
        current_position = context.portfolio.positions[stock].amount
        
        # RSI is above 70 and we own shares, time to sell
        if rsi > context.HIGH_RSI and current_position > 0 and data.can_trade(stock):
            order_target(stock, 0)
   
        # RSI is below 30 and we don't have any shares, time to buy
        elif rsi < context.LOW_RSI and current_position == 0 and data.can_trade(stock):
            order_target_percent(stock, context.securities[stock])

    # record the current RSI values of each stock for later ispection
    record(vb_rsi=rsis[symbol('SPY')],
           tlt_rsi=rsis[symbol('TLT')],
           ief_rsi=rsis[symbol('IEF')],
           gld_rsi=rsis[symbol('GLD')],
           dbc_rsi=rsis[symbol('DBC')],
          )
```
I ran the above code using the following command

```
zipline run -f backtest-erol.py --start 2014-1-1 --end 2018-1-1 --no-benchmark -o myperf.pickle --bundle custom-bundle
```

The custom-bundle has the price history for the relevant tickers. During execution, I get the following exception

```
/Users/rnu/Documents/virtualenv3/financials/lib/python3.8/site-packages/empyrical/stats.py:710: RuntimeWarning: invalid value encountered in true_divide
  np.divide(
/Users/rnu/Documents/virtualenv3/financials/lib/python3.8/site-packages/empyrical/stats.py:799: RuntimeWarning: invalid value encountered in true_divide
  np.divide(average_annual_return, annualized_downside_risk, out=out)
Traceback (most recent call last):
  File "/Users/rnu/Documents/virtualenv3/financials/bin/zipline", line 8, in <module>
    sys.exit(main())
  File "/Users/rnu/Documents/virtualenv3/financials/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rnu/Documents/virtualenv3/financials/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/rnu/Documents/virtualenv3/financials/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rnu/Documents/virtualenv3/financials/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rnu/Documents/virtualenv3/financials/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/rnu/Documents/virtualenv3/financials/lib/python3.8/site-packages/zipline/__main__.py", line 106, in _
    return f(*args, **kwargs)
  File "/Users/rnu/Documents/virtualenv3/financials/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/rnu/Documents/virtualenv3/financials/lib/python3.8/site-packages/zipline/__main__.py", line 300, in run
    return _run(
  File "/Users/rnu/Documents/virtualenv3/financials/lib/python3.8/site-packages/zipline/utils/run_algo.py", line 200, in _run
    perf = TradingAlgorithm(
  File "/Users/rnu/Documents/virtualenv3/financials/lib/python3.8/site-packages/zipline/algorithm.py", line 624, in run
    for perf in self.get_generator():
  File "/Users/rnu/Documents/virtualenv3/financials/lib/python3.8/site-packages/zipline/gens/tradesimulation.py", line 228, in transform
    for capital_change_packet in every_bar(dt):
  File "/Users/rnu/Documents/virtualenv3/financials/lib/python3.8/site-packages/zipline/gens/tradesimulation.py", line 143, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/Users/rnu/Documents/virtualenv3/financials/lib/python3.8/site-packages/zipline/utils/events.py", line 206, in handle_data
    event.handle_data(
  File "/Users/rnu/Documents/virtualenv3/financials/lib/python3.8/site-packages/zipline/utils/events.py", line 229, in handle_data
    self.callback(context, data)
  File "/Users/rnu/Documents/virtualenv3/financials/lib/python3.8/site-packages/zipline/algorithm.py", line 447, in handle_data
    self._handle_data(self, data)
  File "backtest-erol.py", line 57, in handle_data
    order_target_percent(stock, context.securities[stock])
KeyError: Equity(0 [DBC])
```
Has anyone tried zipline backtest with custom portfolio and trading strategy? Is this a bug or am I making some mistake?

Sincerely,
Ramki

**Comment by stefan-jansen** [comment]
Please see examples [here](https://github.com/stefan-jansen/machine-learning-for-trading/tree/main/08_ml4t_workflow)  on using custom bundles.
