### ISSUE TITLE
Backtesting only begins in 1990 despite early start_session parameter

### ISSUE THREAD

**Issue by RichardDale** [stefan-jansen/zipline-reloaded#74]
# Environment

<details>
* Operating System: Windows 11
* Python Version: 3.8
* Python Bitness: 64
* How did you install Zipline: pip
* Zipline: 2.2
</details>

# Description of Issue

Backtesting only begins in 1990 despite despite early start_session parameter being defined for the bundle being defined.

## What steps have you taken to resolve this already?

Issue appears to due to a logic flaw in data/bundles/core.py line 375, within ingest()

`        calendar = get_calendar(bundle.calendar_name)`

then, start_session is limited by the range of dates within the previous retrieved calendar.

The logic flaw here is that get_calendar won't retrieve the full set of dates for the exchange name provider - it only provides a subset by default.

The (easy) fix is to pass the start_session into get_calendar so that the calendar actually reflects the dates requested by the bundle.

`        calendar = get_calendar(bundle.calendar_name,start=bundle.start_session)`

(this allows ingesting back to 1970 - other issues occur if trying beyond this)

If required, I'll provide a one line Pull Request to fix this....

(ref to exchange_calendars report: https://github.com/gerrymanoim/exchange_calendars/issues/112 )

**Comment by stefan-jansen** [comment]
PR would be welcome.
