### ISSUE TITLE
ENH: Allow Futures root symbols to be > 3 characters

### ISSUE THREAD

**Issue by RichardDale** [stefan-jansen/zipline-reloaded#76]
Zipline has a in-built limitation of two characters for root_symbol, despite the database schemas being more flexible.

As more futures are listed, especially on CME with Micro contracts, they are given 3 (or 4) letter symbols, thus requiring an artificial mapping to a 2 letter construct.

This enhancement request is to extend the root symbol to up to 4 characters within Zipline.

For reference, the current database schema has been nicely diagrammed here:
https://github.com/stefan-jansen/zipline-reloaded/discussions/44

**Comment by MBounouar** [comment]
Hi Richard,
I suspect that's where the  dark magic is happening
https://github.com/stefan-jansen/zipline-reloaded/blob/b05579f161f17b61c8651ea7be28b49d7432a28e/src/zipline/assets/assets.py#L243

**Comment by RichardDale** [comment]
Dark magic indeed!

I'm not quite sure why they were trying to save a few bits here and there on a structure only to be used a few hundred times (at most) versus the price data which could amount to many orders of magnitude more data.

**Comment by MBounouar** [comment]
Without any help from the original team it's a bit of a archeological endeavor :smile: , a lot of second guesses when looking at the code but also lot of condensed knowledge to learn from. 
I wouldn't mind taking a shot at it, but I honestly, I don't know when I will manage to find some time in the next months.
I originally wanted to see if it's possible or reasonable to get rid of bcolz (defunct) replacing it with hdf5.
What could also be improved is the futures tests.

**Comment by stefan-jansen** [comment]
Closing for now until we have the man or womanpower to take on enhancements. Contributions welcome!

**Comment by MBounouar** [comment]
> Closing for now until we have the man or womanpower to take on enhancements. Contributions welcome!

Actually, I have fixed it already in #91

**Comment by stefan-jansen** [comment]
Of course you did :)
