### ISSUE TITLE
Live/Paper Trading

### ISSUE THREAD

**Issue by noowfel** [stefan-jansen/zipline-reloaded#81]
Dear Zipline Maintainers,

Just wondering if there is an example of live trading with this library ? I cannot find one. Any help ?

Sincerely,
noowfel

**Comment by MBounouar** [comment]
There isn't.
It should be possible to hook it to brokers like Interactive Brokers

**Comment by noowfel** [comment]
Do you know where I can find the documentation about the class/function to use?
Thanks

**Comment by MBounouar** [comment]
There are several forks of zipline that implement the functionality, best to look at them directly. For instance, 
https://github.com/zipline-live/zipline

**Comment by noowfel** [comment]
Thank you. I think I might keep on using Backtrader but I am also tempted by quantconnect. May I ask what do you use/recommend ?

**Comment by noowfel** [comment]
Looks good !
