### ISSUE TITLE
%zipline ingest -b quandl issue

### ISSUE THREAD

**Issue by majfeizatgmaildotcom** [stefan-jansen/zipline-reloaded#84]
Dear Zipline Maintainers,
I just installed zipline package per Manning requirement virtual env. when  I run the following code I got this error. Anybody know how to resolve the issue? I run this code with both % and !. when I use $  the code did not work at all.
a)
%zipline ingest -b quandl

UsageError                                Traceback (most recent call last)
~\AppData\Local\Temp\tmpfmgovkb0/ipykernel_18392/233775099.py in <module>
----> 1 get_ipython().run_line_magic('zipline', 'ingest -b quandl')

~\anaconda3\envs\liveproject\lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2362                 kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2363             with self.builtin_trap:
-> 2364                 result = fn(*args, **kwargs)
   2365             return result
   2366 

~\anaconda3\envs\liveproject\lib\site-packages\zipline\__main__.py in zipline_magic(line, cell)
    333     )
    334     try:
--> 335         return run.main(
    336             # put our overrides at the start of the parameter list so that
    337             # users may pass values with higher precedence

~\anaconda3\envs\liveproject\lib\site-packages\click\core.py in main(self, args, prog_name, complete_var, standalone_mode, windows_expand_args, **extra)
   1050         try:
   1051             try:
-> 1052                 with self.make_context(prog_name, args, **extra) as ctx:
   1053                     rv = self.invoke(ctx)
   1054                     if not standalone_mode:

~\anaconda3\envs\liveproject\lib\site-packages\click\core.py in make_context(self, info_name, args, parent, **extra)
    912 
    913         with ctx.scope(cleanup=False):
--> 914             self.parse_args(ctx, args)
    915         return ctx
    916 

~\anaconda3\envs\liveproject\lib\site-packages\click\core.py in parse_args(self, ctx, args)
   1371 
   1372         if args and not ctx.allow_extra_args and not ctx.resilient_parsing:
-> 1373             ctx.fail(
   1374                 ngettext(
   1375                     "Got unexpected extra argument ({args})",

~\anaconda3\envs\liveproject\lib\site-packages\click\core.py in fail(self, message)
    671         :param message: the error message to fail with.
    672         """
--> 673         raise UsageError(message, self)
    674 
    675     def abort(self) -> "te.NoReturn":

UsageError: Got unexpected extra argument (ingest)

--------------------------------------------------------------------------------

b) !zipline ingest -b quandl

[2022-02-15 22:48:56.606184] INFO: zipline.data.bundles.core: Ingesting quandl.
Traceback (most recent call last):
  File "C:\Users\Owner\anaconda3\envs\liveproject\Scripts\zipline-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Owner\anaconda3\envs\liveproject\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Owner\anaconda3\envs\liveproject\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\Owner\anaconda3\envs\liveproject\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Owner\anaconda3\envs\liveproject\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Owner\anaconda3\envs\liveproject\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Owner\anaconda3\envs\liveproject\lib\site-packages\zipline\__main__.py", line 389, in ingest
    bundles_module.ingest(
  File "C:\Users\Owner\anaconda3\envs\liveproject\lib\site-packages\zipline\data\bundles\core.py", line 445, in ingest
    bundle.ingest(
  File "C:\Users\Owner\anaconda3\envs\liveproject\lib\site-packages\zipline\data\bundles\quandl.py", line 180, in quandl_bundle
    raise ValueError(
ValueError: Please set your QUANDL_API_KEY environment variable and retry.

**Comment by kriegersaurusrex** [comment]
I was able to get it to work in a Jupyter notebook installed through Anaconda (I used the Anaconda installer with python 3.8.8 & had to modify the python version that the liveproject.yml file wanted), put these a cell and run them:

import quandl
import os

os.environ['QUANDL_API_KEY'] = 'API_KEY'
tsla = quandl.get('WIKI/TSLA', start_date = "2010-06-29", end_date = "2018-03-27")

Ingesting the full quandl set gave me some problems, but there's better data providers out there & I'm only using this to learn how everything works.

**Comment by stefan-jansen** [comment]
The notebook command is (note `!` instead of `%`:
```
!zipline ingest -b quandl
```
