### ISSUE TITLE
Install from conda doesn't work with h5py 3.2.1 but only with version 3.2.0

### ISSUE THREAD

**Issue by data-stepper** [stefan-jansen/zipline-reloaded#92]
Hello fellow pythonistas,

so I just tried to install zipline-reloaded in a fresh conda environment on python 3.9.11 and it failed because it installed h5py version 3.2.1.

After some search I [found](https://github.com/conda-forge/h5py-feedstock/issues/92) that there is some dependency issue regarding that module. After this install I just had to run `pip install h5py==3.2.0` and it fixed the issue.

Just wanted to let you know of this dependency issue, maybe a quick update to the requirements.txt or the conda equivalent can fix the issue?

Thanks for maintaining this nice library installable !

**Comment by stefan-jansen** [comment]
We have just updated Zipline to 2.4 (currently [in beta](https://pypi.org/project/zipline-reloaded/2.4.0b1/)) and should have the [new version up on conda-forge](https://github.com/conda-forge/staged-recipes/pull/21707) in a week or so pending a new exchange-calendar release.
