### ISSUE TITLE
UsageError: Line magic function `%%zipline` not found.

### ISSUE THREAD

**Issue by threehappy** [stefan-jansen/zipline-reloaded#93]
input:
%%zipline --start 2015-1-1 --end 2018-1-1 --output single_factor.pickle --no-benchmark --bundle quandl

output:
UsageError: Line magic function `%%zipline` not found.

i am crazy by the error.

**Comment by MBounouar** [comment]
try
%zipline --start 2015-1-1 --end 2018-1-1 --output single_factor.pickle --no-benchmark --bundle quandl

**Comment by threehappy** [comment]
ValueError: no data for bundle 'quandl' on or before 2022-04-04 13:48:46.907719+00:00
maybe you need to run: $ zipline ingest -b quandl


thanks,but happend a new error as above when i use "%zipline --start 2015-1-1 --end 2018-1-1 --output single_factor.pickle --no-benchmark --bundle quandl".

**Comment by stefan-jansen** [comment]
This is most likely due to local environment / path issues rather than the Zipline library itself, so closing for now unless we get more information that would permit us to replicate and address library failures.
